package com.deppon.dpm.module.projecttools.shared.domain;

import com.deppon.foss.framework.entity.BaseEntity;

/**
 * 
 * 年度规划资源信息
 * @author 150970
 * @date 2015年1月5日 下午1:34:31
 * @since
 * @version
 */
public class AnnualPlanRes2Entity extends BaseEntity {
	/**
	 * 序列化ID
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res2.AI_ID
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    private Integer aiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res2.project_id
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res2.cost_for
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    private Integer costFor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res2.cost_cnt
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    private Long costCnt;
    
    private String costForLabel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res2.AI_ID
     *
     * @return the value of dotp_gh_project_res2.AI_ID
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public Integer getAiId() {
        return aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res2.AI_ID
     *
     * @param aiId the value for dotp_gh_project_res2.AI_ID
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public void setAiId(Integer aiId) {
        this.aiId = aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res2.project_id
     *
     * @return the value of dotp_gh_project_res2.project_id
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res2.project_id
     *
     * @param projectId the value for dotp_gh_project_res2.project_id
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res2.cost_for
     *
     * @return the value of dotp_gh_project_res2.cost_for
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public Integer getCostFor() {
        return costFor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res2.cost_for
     *
     * @param costFor the value for dotp_gh_project_res2.cost_for
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public void setCostFor(Integer costFor) {
        this.costFor = costFor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res2.cost_cnt
     *
     * @return the value of dotp_gh_project_res2.cost_cnt
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public Long getCostCnt() {
        return costCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res2.cost_cnt
     *
     * @param costCnt the value for dotp_gh_project_res2.cost_cnt
     *
     * @mbggenerated Thu Dec 11 15:55:26 CST 2014
     */
    public void setCostCnt(Long costCnt) {
        this.costCnt = costCnt;
    }

	public String getCostForLabel() {
		return costForLabel;
	}

	public void setCostForLabel(String costForLabel) {
		this.costForLabel = costForLabel;
	}
}