package com.deppon.dpm.module.projecttools.shared.domain;

import com.deppon.foss.framework.entity.BaseEntity;

/**
 * 
 * 年度规划资源信息
 * @author 150970
 * @date 2015年1月5日 下午1:34:11
 * @since
 * @version
 */
public class AnnualPlanRes1Entity extends BaseEntity {
	/**
	 * 序列化ID
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res1.AI_ID
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    private Integer aiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res1.project_id
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res1.emp_role
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    private Integer empRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res1.emp_grade
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    private Integer empGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res1.gh_year
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    private Integer ghYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res1.month_cnt
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    private String monthCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_res1.total_cnt
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    private Long totalCnt;
    
    //==================================
    private String empRoleLabel;
    private String empGradeLabel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res1.AI_ID
     *
     * @return the value of dotp_gh_project_res1.AI_ID
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public Integer getAiId() {
        return aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res1.AI_ID
     *
     * @param aiId the value for dotp_gh_project_res1.AI_ID
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public void setAiId(Integer aiId) {
        this.aiId = aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res1.project_id
     *
     * @return the value of dotp_gh_project_res1.project_id
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res1.project_id
     *
     * @param projectId the value for dotp_gh_project_res1.project_id
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res1.emp_role
     *
     * @return the value of dotp_gh_project_res1.emp_role
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public Integer getEmpRole() {
        return empRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res1.emp_role
     *
     * @param empRole the value for dotp_gh_project_res1.emp_role
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public void setEmpRole(Integer empRole) {
        this.empRole = empRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res1.emp_grade
     *
     * @return the value of dotp_gh_project_res1.emp_grade
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public Integer getEmpGrade() {
        return empGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res1.emp_grade
     *
     * @param empGrade the value for dotp_gh_project_res1.emp_grade
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public void setEmpGrade(Integer empGrade) {
        this.empGrade = empGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res1.gh_year
     *
     * @return the value of dotp_gh_project_res1.gh_year
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public Integer getGhYear() {
        return ghYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res1.gh_year
     *
     * @param ghYear the value for dotp_gh_project_res1.gh_year
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public void setGhYear(Integer ghYear) {
        this.ghYear = ghYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res1.month_cnt
     *
     * @return the value of dotp_gh_project_res1.month_cnt
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public String getMonthCnt() {
        return monthCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res1.month_cnt
     *
     * @param monthCnt the value for dotp_gh_project_res1.month_cnt
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public void setMonthCnt(String monthCnt) {
        this.monthCnt = monthCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_res1.total_cnt
     *
     * @return the value of dotp_gh_project_res1.total_cnt
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public Long getTotalCnt() {
        return totalCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_res1.total_cnt
     *
     * @param totalCnt the value for dotp_gh_project_res1.total_cnt
     *
     * @mbggenerated Thu Dec 11 15:54:10 CST 2014
     */
    public void setTotalCnt(Long totalCnt) {
        this.totalCnt = totalCnt;
    }

	public String getEmpRoleLabel() {
		return empRoleLabel;
	}

	public void setEmpRoleLabel(String empRoleLabel) {
		this.empRoleLabel = empRoleLabel;
	}

	public String getEmpGradeLabel() {
		return empGradeLabel;
	}

	public void setEmpGradeLabel(String empGradeLabel) {
		this.empGradeLabel = empGradeLabel;
	}
}