package com.deppon.dpm.module.projecttools.shared.domain;

import com.deppon.foss.framework.entity.BaseEntity;
/**
 * 
 * 项目信息实体类
 * @author 150970
 * @date 2014年10月23日 下午1:57:18
 * @since
 * @version
 */
public class AnnualPlanExtra2 extends BaseEntity {

	/**
	 * 序列化ID
	 */
	private static final long serialVersionUID = 1L;
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_extra2.AI_ID
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    private Integer aiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_extra2.project_id
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_extra2.gh_context
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    private String ghContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_gh_project_extra2.gh_objective
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    private String ghObjective;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_extra2.AI_ID
     *
     * @return the value of dotp_gh_project_extra2.AI_ID
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public Integer getAiId() {
        return aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_extra2.AI_ID
     *
     * @param aiId the value for dotp_gh_project_extra2.AI_ID
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public void setAiId(Integer aiId) {
        this.aiId = aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_extra2.project_id
     *
     * @return the value of dotp_gh_project_extra2.project_id
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_extra2.project_id
     *
     * @param projectId the value for dotp_gh_project_extra2.project_id
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_extra2.gh_context
     *
     * @return the value of dotp_gh_project_extra2.gh_context
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public String getGhContext() {
        return ghContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_extra2.gh_context
     *
     * @param ghContext the value for dotp_gh_project_extra2.gh_context
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public void setGhContext(String ghContext) {
        this.ghContext = ghContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_gh_project_extra2.gh_objective
     *
     * @return the value of dotp_gh_project_extra2.gh_objective
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public String getGhObjective() {
        return ghObjective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_gh_project_extra2.gh_objective
     *
     * @param ghObjective the value for dotp_gh_project_extra2.gh_objective
     *
     * @mbggenerated Wed Nov 12 11:48:01 CST 2014
     */
    public void setGhObjective(String ghObjective) {
        this.ghObjective = ghObjective;
    }
}
