package com.deppon.dpm.module.projecttools.shared.domain;

import com.deppon.foss.framework.entity.BaseEntity;

/**
 * 
 * 项目风险实体类
 * @author 150970
 * @date 2015年1月5日 下午12:15:33
 * @since
 * @version
 */
public class ProjectRiskEntity extends BaseEntity {
	/**
	 * 序列化ID
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_risk.risk_id
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    private Integer riskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_risk.project_code
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_risk.milestone
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    private Integer milestone;
    private String milestonename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_risk.risk_type
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    private Integer riskType;
    private String  riskTypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_risk.risk_level
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    private Integer riskLevel;
    private String riskLevelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_risk.risk_summary
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    private String riskSummary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_risk.risk_id
     *
     * @return the value of dotp_pm_project_risk.risk_id
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public Integer getRiskId() {
        return riskId;
    }

    /**
	 * @return the milestonename
	 */
	public String getMilestonename() {
		return milestonename;
	}

	/**
	 * @param milestonename
	 */
	public void setMilestonename(String milestonename) {
		this.milestonename = milestonename;
	}

	/**
	 * @return the riskTypename
	 */
	public String getRiskTypename() {
		return riskTypename;
	}

	/**
	 * @param riskTypename
	 */
	public void setRiskTypename(String riskTypename) {
		this.riskTypename = riskTypename;
	}

	/**
	 * @return the riskLevelname
	 */
	public String getRiskLevelname() {
		return riskLevelname;
	}

	/**
	 * @param riskLevelname
	 */
	public void setRiskLevelname(String riskLevelname) {
		this.riskLevelname = riskLevelname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_risk.risk_id
     *
     * @param riskId the value for dotp_pm_project_risk.risk_id
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public void setRiskId(Integer riskId) {
        this.riskId = riskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_risk.project_code
     *
     * @return the value of dotp_pm_project_risk.project_code
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_risk.project_code
     *
     * @param projectCode the value for dotp_pm_project_risk.project_code
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_risk.milestone
     *
     * @return the value of dotp_pm_project_risk.milestone
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public Integer getMilestone() {
        return milestone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_risk.milestone
     *
     * @param milestone the value for dotp_pm_project_risk.milestone
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public void setMilestone(Integer milestone) {
        this.milestone = milestone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_risk.risk_type
     *
     * @return the value of dotp_pm_project_risk.risk_type
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public Integer getRiskType() {
        return riskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_risk.risk_type
     *
     * @param riskType the value for dotp_pm_project_risk.risk_type
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public void setRiskType(Integer riskType) {
        this.riskType = riskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_risk.risk_level
     *
     * @return the value of dotp_pm_project_risk.risk_level
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public Integer getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_risk.risk_level
     *
     * @param riskLevel the value for dotp_pm_project_risk.risk_level
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public void setRiskLevel(Integer riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_risk.risk_summary
     *
     * @return the value of dotp_pm_project_risk.risk_summary
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public String getRiskSummary() {
        return riskSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_risk.risk_summary
     *
     * @param riskSummary the value for dotp_pm_project_risk.risk_summary
     *
     * @mbggenerated Thu Nov 13 22:55:52 CST 2014
     */
    public void setRiskSummary(String riskSummary) {
        this.riskSummary = riskSummary;
    }
}