package com.deppon.wfs.workflow.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
* @title: Bankaccount 
* @description：TODO
* @author： 赵慧
* @date： 2013-11-1 下午08:40:27
*/
public class Bankaccount extends Entity {
    /**
     * id
     */
    private String busino;

    /**
     * 工作流号
     */
    private Long processinstid;

    /**
     * 申请人姓名
     */
    private String applyPersonName;

    /**
     * 申请人工号
     */
    private String applyPersonId;

    /**
     *申请人部门
     */
    private String applyDepartment;

    /**
     *  挂靠营业部标杆编码
     */
    private String applyDepartmentFinasyscode;

    /**
     * 所属财务部
     */
    private String belongFinanceDepartment;

    /**
     *财务部标杆编码
     */
    private String financeFinasyscode;

    /**
     * 申请类型
     */
    private String applyType;

    /**
     * 账户类型
     */
    private String accountType;

    /**
     * 账户属性
     */
    private String accountAttribute;

    /**
     *挂靠营业部
     */
    private String salesDepartment;

    /**
     *开户银行
     */
    private String openAccountBank;

    /**
     * 银行名称
     */
    private String bankName;

    /**
     * 开户名
     */
    private String openAccountUser;

    /**
     * 银行账号
     */
    private String bankAccount;

    /**
     * 开户地区
     */
    private String openAccountAddress;

    /**
     * 账户性质
     */
    private String accountProperty;

    /**
     * 收支性质
     */
    private String inOutProperty;

    /**
     * 申请原因
     */
    private String applyReason;

    /**
     *创建时间
     */
    private Date creatTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 业务状态
     */
    private String isseffective;

    /**
     * 备用字段1
     */
    private BigDecimal reserveOne;

    /**
     * 备用字段2
     */
    private String reserveTwo;

    /**
     *备用字段3
     */
    private String reserveThree;
    /**
     *银行账号（审批）
     */
    private String bankAccountApproval;
    /**
     *开户支行
     */
    private String openAccountBranch;
    /**
     *开户日期
     */
    private Date openAccountDate;
    /**
     *活期定期
     */
    private String currentOrTeminal;
    /**
     *销户日期
     */
    private Date closingDate;

    /**
     * 老表数据：存款方式
     * */
    private String accountDeposit;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.BUSINO
     *
     * @return the value of T_WFS_BANKACCOUNT.BUSINO
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.BUSINO
     *
     * @param busino the value for T_WFS_BANKACCOUNT.BUSINO
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.PROCESSINSTID
     *
     * @return the value of T_WFS_BANKACCOUNT.PROCESSINSTID
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public Long getProcessinstid() {
        return processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.PROCESSINSTID
     *
     * @param processinstid the value for T_WFS_BANKACCOUNT.PROCESSINSTID
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setProcessinstid(Long processinstid) {
        this.processinstid = processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.APPLY_PERSON_NAME
     *
     * @return the value of T_WFS_BANKACCOUNT.APPLY_PERSON_NAME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.APPLY_PERSON_NAME
     *
     * @param applyPersonName the value for T_WFS_BANKACCOUNT.APPLY_PERSON_NAME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.APPLY_PERSON_ID
     *
     * @return the value of T_WFS_BANKACCOUNT.APPLY_PERSON_ID
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getApplyPersonId() {
        return applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.APPLY_PERSON_ID
     *
     * @param applyPersonId the value for T_WFS_BANKACCOUNT.APPLY_PERSON_ID
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setApplyPersonId(String applyPersonId) {
        this.applyPersonId = applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.APPLY_DEPARTMENT
     *
     * @return the value of T_WFS_BANKACCOUNT.APPLY_DEPARTMENT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getApplyDepartment() {
        return applyDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.APPLY_DEPARTMENT
     *
     * @param applyDepartment the value for T_WFS_BANKACCOUNT.APPLY_DEPARTMENT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setApplyDepartment(String applyDepartment) {
        this.applyDepartment = applyDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.APPLY_DEPARTMENT_FINASYSCODE
     *
     * @return the value of T_WFS_BANKACCOUNT.APPLY_DEPARTMENT_FINASYSCODE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getApplyDepartmentFinasyscode() {
        return applyDepartmentFinasyscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.APPLY_DEPARTMENT_FINASYSCODE
     *
     * @param applyDepartmentFinasyscode the value for T_WFS_BANKACCOUNT.APPLY_DEPARTMENT_FINASYSCODE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setApplyDepartmentFinasyscode(String applyDepartmentFinasyscode) {
        this.applyDepartmentFinasyscode = applyDepartmentFinasyscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.BELONG_FINANCE_DEPARTMENT
     *
     * @return the value of T_WFS_BANKACCOUNT.BELONG_FINANCE_DEPARTMENT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getBelongFinanceDepartment() {
        return belongFinanceDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.BELONG_FINANCE_DEPARTMENT
     *
     * @param belongFinanceDepartment the value for T_WFS_BANKACCOUNT.BELONG_FINANCE_DEPARTMENT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setBelongFinanceDepartment(String belongFinanceDepartment) {
        this.belongFinanceDepartment = belongFinanceDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.FINANCE_FINASYSCODE
     *
     * @return the value of T_WFS_BANKACCOUNT.FINANCE_FINASYSCODE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getFinanceFinasyscode() {
        return financeFinasyscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.FINANCE_FINASYSCODE
     *
     * @param financeFinasyscode the value for T_WFS_BANKACCOUNT.FINANCE_FINASYSCODE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setFinanceFinasyscode(String financeFinasyscode) {
        this.financeFinasyscode = financeFinasyscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.APPLY_TYPE
     *
     * @return the value of T_WFS_BANKACCOUNT.APPLY_TYPE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.APPLY_TYPE
     *
     * @param applyType the value for T_WFS_BANKACCOUNT.APPLY_TYPE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.ACCOUNT_TYPE
     *
     * @return the value of T_WFS_BANKACCOUNT.ACCOUNT_TYPE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.ACCOUNT_TYPE
     *
     * @param accountType the value for T_WFS_BANKACCOUNT.ACCOUNT_TYPE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.ACCOUNT_ATTRIBUTE
     *
     * @return the value of T_WFS_BANKACCOUNT.ACCOUNT_ATTRIBUTE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getAccountAttribute() {
        return accountAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.ACCOUNT_ATTRIBUTE
     *
     * @param accountAttribute the value for T_WFS_BANKACCOUNT.ACCOUNT_ATTRIBUTE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setAccountAttribute(String accountAttribute) {
        this.accountAttribute = accountAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.SALES_DEPARTMENT
     *
     * @return the value of T_WFS_BANKACCOUNT.SALES_DEPARTMENT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getSalesDepartment() {
        return salesDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.SALES_DEPARTMENT
     *
     * @param salesDepartment the value for T_WFS_BANKACCOUNT.SALES_DEPARTMENT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setSalesDepartment(String salesDepartment) {
        this.salesDepartment = salesDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @return the value of T_WFS_BANKACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getOpenAccountBank() {
        return openAccountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @param openAccountBank the value for T_WFS_BANKACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setOpenAccountBank(String openAccountBank) {
        this.openAccountBank = openAccountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.BANK_NAME
     *
     * @return the value of T_WFS_BANKACCOUNT.BANK_NAME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.BANK_NAME
     *
     * @param bankName the value for T_WFS_BANKACCOUNT.BANK_NAME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.OPEN_ACCOUNT_USER
     *
     * @return the value of T_WFS_BANKACCOUNT.OPEN_ACCOUNT_USER
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getOpenAccountUser() {
        return openAccountUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.OPEN_ACCOUNT_USER
     *
     * @param openAccountUser the value for T_WFS_BANKACCOUNT.OPEN_ACCOUNT_USER
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setOpenAccountUser(String openAccountUser) {
        this.openAccountUser = openAccountUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.BANK_ACCOUNT
     *
     * @return the value of T_WFS_BANKACCOUNT.BANK_ACCOUNT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.BANK_ACCOUNT
     *
     * @param bankAccount the value for T_WFS_BANKACCOUNT.BANK_ACCOUNT
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.OPEN_ACCOUNT_ADDRESS
     *
     * @return the value of T_WFS_BANKACCOUNT.OPEN_ACCOUNT_ADDRESS
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getOpenAccountAddress() {
        return openAccountAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.OPEN_ACCOUNT_ADDRESS
     *
     * @param openAccountAddress the value for T_WFS_BANKACCOUNT.OPEN_ACCOUNT_ADDRESS
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setOpenAccountAddress(String openAccountAddress) {
        this.openAccountAddress = openAccountAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.ACCOUNT_PROPERTY
     *
     * @return the value of T_WFS_BANKACCOUNT.ACCOUNT_PROPERTY
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getAccountProperty() {
        return accountProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.ACCOUNT_PROPERTY
     *
     * @param accountProperty the value for T_WFS_BANKACCOUNT.ACCOUNT_PROPERTY
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setAccountProperty(String accountProperty) {
        this.accountProperty = accountProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.IN_OUT_PROPERTY
     *
     * @return the value of T_WFS_BANKACCOUNT.IN_OUT_PROPERTY
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getInOutProperty() {
        return inOutProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.IN_OUT_PROPERTY
     *
     * @param inOutProperty the value for T_WFS_BANKACCOUNT.IN_OUT_PROPERTY
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setInOutProperty(String inOutProperty) {
        this.inOutProperty = inOutProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.APPLY_REASON
     *
     * @return the value of T_WFS_BANKACCOUNT.APPLY_REASON
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getApplyReason() {
        return applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.APPLY_REASON
     *
     * @param applyReason the value for T_WFS_BANKACCOUNT.APPLY_REASON
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.CREAT_TIME
     *
     * @return the value of T_WFS_BANKACCOUNT.CREAT_TIME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.CREAT_TIME
     *
     * @param creatTime the value for T_WFS_BANKACCOUNT.CREAT_TIME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.MODIFY_TIME
     *
     * @return the value of T_WFS_BANKACCOUNT.MODIFY_TIME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_BANKACCOUNT.MODIFY_TIME
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.ISSEFFECTIVE
     *
     * @return the value of T_WFS_BANKACCOUNT.ISSEFFECTIVE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_BANKACCOUNT.ISSEFFECTIVE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.RESERVE_ONE
     *
     * @return the value of T_WFS_BANKACCOUNT.RESERVE_ONE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public BigDecimal getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.RESERVE_ONE
     *
     * @param reserveOne the value for T_WFS_BANKACCOUNT.RESERVE_ONE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setReserveOne(BigDecimal reserveOne) {
        this.reserveOne = reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.RESERVE_TWO
     *
     * @return the value of T_WFS_BANKACCOUNT.RESERVE_TWO
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.RESERVE_TWO
     *
     * @param reserveTwo the value for T_WFS_BANKACCOUNT.RESERVE_TWO
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_BANKACCOUNT.RESERVE_THREE
     *
     * @return the value of T_WFS_BANKACCOUNT.RESERVE_THREE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_BANKACCOUNT.RESERVE_THREE
     *
     * @param reserveThree the value for T_WFS_BANKACCOUNT.RESERVE_THREE
     *
     * @mbggenerated Fri Nov 01 20:32:55 CST 2013
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree;
    }

	/**
	 * @return the bankAccountApproval
	 */
	public String getBankAccountApproval() {
		return bankAccountApproval;
	}

	/**
	 * @param bankAccountApproval the bankAccountApproval to set
	 */
	public void setBankAccountApproval(String bankAccountApproval) {
		this.bankAccountApproval = bankAccountApproval;
	}

	/**
	 * @return the openAccountBranch
	 */
	public String getOpenAccountBranch() {
		return openAccountBranch;
	}

	/**
	 * @param openAccountBranch the openAccountBranch to set
	 */
	public void setOpenAccountBranch(String openAccountBranch) {
		this.openAccountBranch = openAccountBranch;
	}

	/**
	 * @return the openAccountDate
	 */
	public Date getOpenAccountDate() {
		return openAccountDate;
	}

	/**
	 * @param openAccountDate the openAccountDate to set
	 */
	public void setOpenAccountDate(Date openAccountDate) {
		this.openAccountDate = openAccountDate;
	}

	/**
	 * @return the currentOrTeminal
	 */
	public String getCurrentOrTeminal() {
		return currentOrTeminal;
	}

	/**
	 * @param currentOrTeminal the currentOrTeminal to set
	 */
	public void setCurrentOrTeminal(String currentOrTeminal) {
		this.currentOrTeminal = currentOrTeminal;
	}

	/**
	 * @return the closingDate
	 */
	public Date getClosingDate() {
		return closingDate;
	}

	/**
	 * @param closingDate the closingDate to set
	 */
	public void setClosingDate(Date closingDate) {
		this.closingDate = closingDate;
	}

	/**
	 * @return the accountDeposit
	 */
	public String getAccountDeposit() {
		return accountDeposit;
	}

	/**
	 * @param accountDeposit the accountDeposit to set
	 */
	public void setAccountDeposit(String accountDeposit) {
		this.accountDeposit = accountDeposit;
	}
}