
package com.deppon.wfs.workflow.domain; 

import java.math.BigDecimal;
import java.util.Date;
/** 
 * @Title: DismissalBean.java
 * @Package com.deppon.wfs.workflow.domain 
 * @Description: 免职申请
 * @author yinrongping 
 * @date 2014-1-14 下午2:17:13 
 * @version V1.0 
 */
public class DismissalBean extends Entity{
    /**
	* 
	*/
	private static final long serialVersionUID = 1L;

	/**
     * 流程序号，主键
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String busino;

    /**
     * 流程实例ID
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private Long processinstid;

    /**
     * 申请人员工号
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String applyPersonId;

    /**
     * 申请人ID，EMP表的主键
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String applyPersonName;

    /**
     * 申请人ID，EMP表的主键
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private BigDecimal empid;

    /**
     *免职所属本部（通过和需求确认就是以前的‘免职类型’DISMISSALTYPE）
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String dismissalDepartment;
    /**
     *免职所属本部标杆编码（通过和需求确认就是以前的‘免职类型’DISMISSALTYPE）
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String dismissalDepartmentCode;

    /**
     * 被免职人姓名
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String manname;

    /**
     * 被免职人ID
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String mannameId;

    /**
     * 被免职人部门
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String mandept;

    /**
     *被免职人部门ID
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String mandeptid;

    /**
     * 被免职人职位
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String manpost;
    /**
     * 被免职人职位编码（与业务字典对应）
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String manpostCode;

    /**
     *所属人事部
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String personnel;
    /**
     *所属人事部编码
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String personnelCode;
    /**
     *申请事由
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String remark;

    /**
     * 创建时间
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private Date createTime;

    /**
     * 修改时间
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private Date modifyTime;

    /**
     * 业务状态
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String isseffective;

    /**
     *备用字段1
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String spareField1;

    /**
     * 备用字段2
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private String spareField2;

    /**
     * 数字字段（扩展）
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    private BigDecimal subnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.BUSINO
     *
     * @return the value of T_WFS_DISMISSAL.BUSINO
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.BUSINO
     *
     * @param busino the value for T_WFS_DISMISSAL.BUSINO
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.APPLY_PERSON_ID
     *
     * @return the value of T_WFS_DISMISSAL.APPLY_PERSON_ID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getApplyPersonId() {
        return applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.APPLY_PERSON_ID
     *
     * @param applyPersonId the value for T_WFS_DISMISSAL.APPLY_PERSON_ID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setApplyPersonId(String applyPersonId) {
        this.applyPersonId = applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.APPLY_PERSON_NAME
     *
     * @return the value of T_WFS_DISMISSAL.APPLY_PERSON_NAME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.APPLY_PERSON_NAME
     *
     * @param applyPersonName the value for T_WFS_DISMISSAL.APPLY_PERSON_NAME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.EMPID
     *
     * @return the value of T_WFS_DISMISSAL.EMPID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public BigDecimal getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.EMPID
     *
     * @param empid the value for T_WFS_DISMISSAL.EMPID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setEmpid(BigDecimal empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.DISMISSAL_DEPARTMENT
     *
     * @return the value of T_WFS_DISMISSAL.DISMISSAL_DEPARTMENT
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getDismissalDepartment() {
        return dismissalDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.DISMISSAL_DEPARTMENT
     *
     * @param dismissalDepartment the value for T_WFS_DISMISSAL.DISMISSAL_DEPARTMENT
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setDismissalDepartment(String dismissalDepartment) {
        this.dismissalDepartment = dismissalDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.MANNAME
     *
     * @return the value of T_WFS_DISMISSAL.MANNAME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getManname() {
        return manname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.MANNAME
     *
     * @param manname the value for T_WFS_DISMISSAL.MANNAME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setManname(String manname) {
        this.manname = manname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.MANNAME_ID
     *
     * @return the value of T_WFS_DISMISSAL.MANNAME_ID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getMannameId() {
        return mannameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.MANNAME_ID
     *
     * @param mannameId the value for T_WFS_DISMISSAL.MANNAME_ID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setMannameId(String mannameId) {
        this.mannameId = mannameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.MANDEPT
     *
     * @return the value of T_WFS_DISMISSAL.MANDEPT
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getMandept() {
        return mandept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.MANDEPT
     *
     * @param mandept the value for T_WFS_DISMISSAL.MANDEPT
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setMandept(String mandept) {
        this.mandept = mandept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.MANDEPTID
     *
     * @return the value of T_WFS_DISMISSAL.MANDEPTID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getMandeptid() {
        return mandeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.MANDEPTID
     *
     * @param mandeptid the value for T_WFS_DISMISSAL.MANDEPTID
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setMandeptid(String mandeptid) {
        this.mandeptid = mandeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.MANPOST
     *
     * @return the value of T_WFS_DISMISSAL.MANPOST
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getManpost() {
        return manpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.MANPOST
     *
     * @param manpost the value for T_WFS_DISMISSAL.MANPOST
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setManpost(String manpost) {
        this.manpost = manpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.PERSONNEL
     *
     * @return the value of T_WFS_DISMISSAL.PERSONNEL
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getPersonnel() {
        return personnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.PERSONNEL
     *
     * @param personnel the value for T_WFS_DISMISSAL.PERSONNEL
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setPersonnel(String personnel) {
        this.personnel = personnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.REMARK
     *
     * @return the value of T_WFS_DISMISSAL.REMARK
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.REMARK
     *
     * @param remark the value for T_WFS_DISMISSAL.REMARK
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.CREATE_TIME
     *
     * @return the value of T_WFS_DISMISSAL.CREATE_TIME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.CREATE_TIME
     *
     * @param createTime the value for T_WFS_DISMISSAL.CREATE_TIME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.MODIFY_TIME
     *
     * @return the value of T_WFS_DISMISSAL.MODIFY_TIME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_DISMISSAL.MODIFY_TIME
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.ISSEFFECTIVE
     *
     * @return the value of T_WFS_DISMISSAL.ISSEFFECTIVE
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_DISMISSAL.ISSEFFECTIVE
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.SPARE_FIELD1
     *
     * @return the value of T_WFS_DISMISSAL.SPARE_FIELD1
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_DISMISSAL.SPARE_FIELD1
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.SPARE_FIELD2
     *
     * @return the value of T_WFS_DISMISSAL.SPARE_FIELD2
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_DISMISSAL.SPARE_FIELD2
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_DISMISSAL.SUBNUMBER
     *
     * @return the value of T_WFS_DISMISSAL.SUBNUMBER
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public BigDecimal getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_DISMISSAL.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_DISMISSAL.SUBNUMBER
     *
     * @mbggenerated Thu Jan 02 14:53:42 CST 2014
     */
    public void setSubnumber(BigDecimal subnumber) {
        this.subnumber = subnumber;
    }

	/**
	 * @return the processinstid
	 */
	public Long getProcessinstid() {
		return processinstid;
	}

	/**
	 * @param processinstid the processinstid to set
	 */
	public void setProcessinstid(Long processinstid) {
		this.processinstid = processinstid;
	}

	/**
	 * @return the personnelCode
	 */
	public String getPersonnelCode() {
		return personnelCode;
	}

	/**
	 * @param personnelCode the personnelCode to set
	 */
	public void setPersonnelCode(String personnelCode) {
		this.personnelCode = personnelCode;
	}

	/**
	 * @return the dismissalDepartmentCode
	 */
	public String getDismissalDepartmentCode() {
		return dismissalDepartmentCode;
	}

	/**
	 * @param dismissalDepartmentCode the dismissalDepartmentCode to set
	 */
	public void setDismissalDepartmentCode(String dismissalDepartmentCode) {
		this.dismissalDepartmentCode = dismissalDepartmentCode;
	}

	/**
	 * @return the manpostCode
	 */
	public String getManpostCode() {
		return manpostCode;
	}

	/**
	 * @param manpostCode the manpostCode to set
	 */
	public void setManpostCode(String manpostCode) {
		this.manpostCode = manpostCode;
	}
}
