
package com.deppon.wfs.workflow.domain; 
/** 
 * @Title: LaywerapplyBean.java
 * @Package com.deppon.wfs.workflow.domain 
 * @Description: 诉讼案件立案/外请律师申请
 * @author yinrongping 
 * @date 2014-1-14 下午2:06:37 
 * @version V1.0 
 */

import java.math.BigDecimal;
import java.util.Date;


public class LaywerapplyBean extends Entity{
    /**
	* 
	*/
	private static final long serialVersionUID = 1L;

	/**
     * 流程序号，主键
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
	
    private String busino;

    /**
     * 流程实例ID
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private Long processinstid;

    /**
     * 申请人员工号
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String applyPersonId;

    /**
     *申请人姓名
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String applyPersonName;

    /**
     *申请人ID，EMP表的主键
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private BigDecimal empid;

    /**
     * 申请类别
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String appCategory;

    /**
     * 申请类别对应业务字典编码
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String appCategoryCode;

    /**
     * 案件名称
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String caseName;

    /**
     * 涉案部门
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String org;

    /**
     * 涉案金额
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private BigDecimal money;

    /**
     * 诉讼费
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private BigDecimal lawsuitmoney;

    /**
     * 案件基本情况
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String basicinfo;

    /**
     * 请示事项
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String applyinfo;

    /**
     * 所属子公司
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String childcompany;

    /**
     * 所属子公司标杆编码
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String childcompanyCode;

    /**
     *申请事由
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String reason;

    /**
     * 创建时间
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private Date createTime;

    /**
     * 修改时间
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private Date modifyTime;

    /**
     *业务状态
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String isseffective;

    /**
     * 备用字段1
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String spareField1;

    /**
     *备用字段2
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private String spareField2;

    /**
     * 数字字段（扩展）
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    private BigDecimal subnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.BUSINO
     *
     * @return the value of T_WFS_LAYWERAPPLY.BUSINO
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.BUSINO
     *
     * @param busino the value for T_WFS_LAYWERAPPLY.BUSINO
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.APPLY_PERSON_ID
     *
     * @return the value of T_WFS_LAYWERAPPLY.APPLY_PERSON_ID
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getApplyPersonId() {
        return applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.APPLY_PERSON_ID
     *
     * @param applyPersonId the value for T_WFS_LAYWERAPPLY.APPLY_PERSON_ID
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setApplyPersonId(String applyPersonId) {
        this.applyPersonId = applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.APPLY_PERSON_NAME
     *
     * @return the value of T_WFS_LAYWERAPPLY.APPLY_PERSON_NAME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.APPLY_PERSON_NAME
     *
     * @param applyPersonName the value for T_WFS_LAYWERAPPLY.APPLY_PERSON_NAME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.EMPID
     *
     * @return the value of T_WFS_LAYWERAPPLY.EMPID
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public BigDecimal getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.EMPID
     *
     * @param empid the value for T_WFS_LAYWERAPPLY.EMPID
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setEmpid(BigDecimal empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.APP_CATEGORY
     *
     * @return the value of T_WFS_LAYWERAPPLY.APP_CATEGORY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getAppCategory() {
        return appCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.APP_CATEGORY
     *
     * @param appCategory the value for T_WFS_LAYWERAPPLY.APP_CATEGORY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setAppCategory(String appCategory) {
        this.appCategory = appCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.APP_CATEGORY_CODE
     *
     * @return the value of T_WFS_LAYWERAPPLY.APP_CATEGORY_CODE
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getAppCategoryCode() {
        return appCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.APP_CATEGORY_CODE
     *
     * @param appCategoryCode the value for T_WFS_LAYWERAPPLY.APP_CATEGORY_CODE
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setAppCategoryCode(String appCategoryCode) {
        this.appCategoryCode = appCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.CASE_NAME
     *
     * @return the value of T_WFS_LAYWERAPPLY.CASE_NAME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.CASE_NAME
     *
     * @param caseName the value for T_WFS_LAYWERAPPLY.CASE_NAME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.ORG
     *
     * @return the value of T_WFS_LAYWERAPPLY.ORG
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getOrg() {
        return org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.ORG
     *
     * @param org the value for T_WFS_LAYWERAPPLY.ORG
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setOrg(String org) {
        this.org = org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.MONEY
     *
     * @return the value of T_WFS_LAYWERAPPLY.MONEY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.MONEY
     *
     * @param money the value for T_WFS_LAYWERAPPLY.MONEY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.LAWSUITMONEY
     *
     * @return the value of T_WFS_LAYWERAPPLY.LAWSUITMONEY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public BigDecimal getLawsuitmoney() {
        return lawsuitmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.LAWSUITMONEY
     *
     * @param lawsuitmoney the value for T_WFS_LAYWERAPPLY.LAWSUITMONEY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setLawsuitmoney(BigDecimal lawsuitmoney) {
        this.lawsuitmoney = lawsuitmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.BASICINFO
     *
     * @return the value of T_WFS_LAYWERAPPLY.BASICINFO
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getBasicinfo() {
        return basicinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.BASICINFO
     *
     * @param basicinfo the value for T_WFS_LAYWERAPPLY.BASICINFO
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setBasicinfo(String basicinfo) {
        this.basicinfo = basicinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.APPLYINFO
     *
     * @return the value of T_WFS_LAYWERAPPLY.APPLYINFO
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getApplyinfo() {
        return applyinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.APPLYINFO
     *
     * @param applyinfo the value for T_WFS_LAYWERAPPLY.APPLYINFO
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setApplyinfo(String applyinfo) {
        this.applyinfo = applyinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.CHILDCOMPANY
     *
     * @return the value of T_WFS_LAYWERAPPLY.CHILDCOMPANY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getChildcompany() {
        return childcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.CHILDCOMPANY
     *
     * @param childcompany the value for T_WFS_LAYWERAPPLY.CHILDCOMPANY
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setChildcompany(String childcompany) {
        this.childcompany = childcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.CHILDCOMPANY_CODE
     *
     * @return the value of T_WFS_LAYWERAPPLY.CHILDCOMPANY_CODE
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getChildcompanyCode() {
        return childcompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.CHILDCOMPANY_CODE
     *
     * @param childcompanyCode the value for T_WFS_LAYWERAPPLY.CHILDCOMPANY_CODE
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setChildcompanyCode(String childcompanyCode) {
        this.childcompanyCode = childcompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.REASON
     *
     * @return the value of T_WFS_LAYWERAPPLY.REASON
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.REASON
     *
     * @param reason the value for T_WFS_LAYWERAPPLY.REASON
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.CREATE_TIME
     *
     * @return the value of T_WFS_LAYWERAPPLY.CREATE_TIME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.CREATE_TIME
     *
     * @param createTime the value for T_WFS_LAYWERAPPLY.CREATE_TIME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.MODIFY_TIME
     *
     * @return the value of T_WFS_LAYWERAPPLY.MODIFY_TIME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_LAYWERAPPLY.MODIFY_TIME
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.ISSEFFECTIVE
     *
     * @return the value of T_WFS_LAYWERAPPLY.ISSEFFECTIVE
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_LAYWERAPPLY.ISSEFFECTIVE
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.SPARE_FIELD1
     *
     * @return the value of T_WFS_LAYWERAPPLY.SPARE_FIELD1
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_LAYWERAPPLY.SPARE_FIELD1
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.SPARE_FIELD2
     *
     * @return the value of T_WFS_LAYWERAPPLY.SPARE_FIELD2
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_LAYWERAPPLY.SPARE_FIELD2
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_LAYWERAPPLY.SUBNUMBER
     *
     * @return the value of T_WFS_LAYWERAPPLY.SUBNUMBER
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public BigDecimal getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_LAYWERAPPLY.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_LAYWERAPPLY.SUBNUMBER
     *
     * @mbggenerated Mon Jan 06 16:34:02 CST 2014
     */
    public void setSubnumber(BigDecimal subnumber) {
        this.subnumber = subnumber;
    }

	/**
	 * @return the processinstid
	 */
	public Long getProcessinstid() {
		return processinstid;
	}

	/**
	 * @param processinstid the processinstid to set
	 */
	public void setProcessinstid(Long processinstid) {
		this.processinstid = processinstid;
	}
}
