package com.deppon.wfs.workflow.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
* @title: NewDeptApplyBean 
* @description：TODO
* @author： 高雅哲
* @date： 2013-10-15 下午2:02:07
*/
public class NewDeptApplyBean extends Entity{
    /**
     *流程序号,主键,含有字母
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String busino;

    /**
     * 流程实例ID，相当于工作流号
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private Long processinstid;

    /**
     * 申请人工号
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String applyPersonId;

    /**
     * 申请人姓名
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String applyPersonName;

    /**
     * 申请人ID
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String empid;

    /**
     * 新成立部门名称
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String newDeptName;

    /**
     *申请人部门号码
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String applyDeptNo;

    /**
     *申请人部门名称
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String applyDeptName;

    /**
     * 申请人职位
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String empPost;

    /**
     *申请事由
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String applyReason;

    /**
     * 创建时间
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private Date createTime;

    /**
     * 修改时间
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private Date modifyTime;

    /**
     * 业务状态
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String isseffective;

    /**
     * 备用字段1
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private Object spareField1;

    /**
     * 备用字段2
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private Object spareField2;

    /**
     * 备用字段（数字类型）
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private BigDecimal subnumber;
    /**
     * 组织架构研究组审批时选择工作流流向
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String applyFlow;
    /**
     * 在选择员配置组时选择重新选择流向重新选择流向
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String applyReflow;
    /**
     * 架构调整类型营业务字典编码
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String deptChangeCode;
    /**
     * 架构调整类型中文
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    private String deptChange;
    
    public String getDeptChangeCode() {
		return deptChangeCode;
	}

	public String getDeptChange() {
		return deptChange;
	}

	public void setDeptChangeCode(String deptChangeCode) {
		this.deptChangeCode = deptChangeCode;
	}

	public void setDeptChange(String deptChange) {
		this.deptChange = deptChange;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.BUSINO
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.BUSINO
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.BUSINO
     *
     * @param busino the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.BUSINO
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }
    /**
	 * @return the processinstid
	 */
	public Long getProcessinstid() {
		return processinstid;
	}

	/**
	 * @param processinstid the processinstid to set
	 */
	public void setProcessinstid(Long processinstid) {
		this.processinstid = processinstid;
	}
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_ID
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_ID
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getApplyPersonId() {
        return applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_ID
     *
     * @param applyPersonId the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_ID
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setApplyPersonId(String applyPersonId) {
        this.applyPersonId = applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_NAME
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_NAME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_NAME
     *
     * @param applyPersonName the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_PERSON_NAME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMPID
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMPID
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMPID
     *
     * @param empid the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMPID
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setEmpid(String empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.NEWDEPT_NAME
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.NEWDEPT_NAME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getNewDeptName() {
        return newDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.NEWDEPT_NAME
     *
     * @param newDeptName the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.NEWDEPT_NAME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setNewDeptName(String newDeptName) {
        this.newDeptName = newDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NO
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NO
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getApplyDeptNo() {
        return applyDeptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NO
     *
     * @param applyDeptNo the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NO
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setApplyDeptNo(String applyDeptNo) {
        this.applyDeptNo = applyDeptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NAME
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NAME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getApplyDeptName() {
        return applyDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NAME
     *
     * @param applyDeptName the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_DEPT_NAME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setApplyDeptName(String applyDeptName) {
        this.applyDeptName = applyDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMP_POST
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMP_POST
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getEmpPost() {
        return empPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMP_POST
     *
     * @param empPost the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.EMP_POST
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setEmpPost(String empPost) {
        this.empPost = empPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_REASON
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_REASON
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getApplyReason() {
        return applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_REASON
     *
     * @param applyReason the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.APPLY_REASON
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.CREATE_TIME
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.CREATE_TIME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.CREATE_TIME
     *
     * @param createTime the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.CREATE_TIME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.MODIFY_TIME
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.MODIFY_TIME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.MODIFY_TIME
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.ISSEFFECTIVE
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.ISSEFFECTIVE
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.ISSEFFECTIVE
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD1
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD1
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public Object getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD1
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setSpareField1(Object spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD2
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD2
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public Object getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.SPARE_FIELD2
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setSpareField2(Object spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.SUBNUMBER
     *
     * @return the value of T_WFS_NEWDEPARTMENTFOUNDAPPLY.SUBNUMBER
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public BigDecimal getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_NEWDEPARTMENTFOUNDAPPLY.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_NEWDEPARTMENTFOUNDAPPLY.SUBNUMBER
     *
     * @mbggenerated Tue Oct 15 13:31:16 CST 2013
     */
    public void setSubnumber(BigDecimal subnumber) {
        this.subnumber = subnumber;
    }
    public NewDeptApplyBean(){
    	
    }

	/**
	 * @return the applyFlow
	 */
	public String getApplyFlow() {
		return applyFlow;
	}

	/**
	 * @param applyFlow the applyFlow to set
	 */
	public void setApplyFlow(String applyFlow) {
		this.applyFlow = applyFlow;
	}

	/**
	 * @return the applyReflow
	 */
	public String getApplyReflow() {
		return applyReflow;
	}

	/**
	 * @param applyReflow the applyReflow to set
	 */
	public void setApplyReflow(String applyReflow) {
		this.applyReflow = applyReflow;
	}
	
}