package com.deppon.wfs.workflow.domain;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;





/**
* @title: OvertimeApplyParentBean 
* @description：TODO
* @author： 高雅哲
* @date： 2013-11-15 下午8:13:14
*/

public class OvertimeApplyParentBean extends Entity{
	
	/**
	 * 存放加班时间信息
	 */
	private List<OvertimeApplyChildBean> overTimeInfoList;
	/** 
	 * 存放加班时间信息的json字符串
	 */
	private String overTimeInfoChild;
    /**
     * 流程序号，主键
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
	
    private String busino;

    /**
     * 流程实例ID
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private Long processinstid;

    /**
     * 申请人员工号
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String applyPersonId;

    /**
     *申请人姓名
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String applyPersonName;

    /**
     * 申请人所在部门
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String dept;

    /**
     *申请人职位
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String position;

    /**
     *申请人empid
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String userid;

    /**
     * 申请类型
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String applyType;
    /**
     * 申请类型编码
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String applyTypeCode;

    /**
     * 申请人所在人事部
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String personnelDept;

    /**
     * 加班工作流号
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String otapplyno;

    /**
     * 平时加班天数
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private BigDecimal workdays;

    /**
     * 周末加班天数
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private BigDecimal holidays;
    /**
     * 法定加班天数
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private BigDecimal legaldays;

    /**
     * 晚班开始日期
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private Date nbeginDate;

    /**
     * 晚班结束日期
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private Date nendDate;

    /**
     *晚班天数
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private BigDecimal nightDays;

    /**
     * 晚班证明人
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String nwitness;
    /**
     * 晚班证明人工号
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String  nwitnessId;

    /**
     * 加班信息
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String otInfomation;

    /**
     * 加班原因
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String reason;

    /**
     * 创建时间
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private Date createTime;

    /**
     * 修改时间
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private Date modifyTime;

    /**
     *业务状态
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String isseffective;

    /**
     * 备用字段1
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String spareField1;

    /**
     * 备用字段2
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private String spareField2;

    /**
     * 数字字段（扩展）
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    private BigDecimal subnumber;
    
    
    //vo
    /**
     * 所属人事部
     */
    private String personnelDeptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.BUSINO
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.BUSINO
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.BUSINO
     *
     * @param busino the value for T_WFS_OVERTIMEAPPLY_PARENT.BUSINO
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.PROCESSINSTID
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.PROCESSINSTID
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public Long getProcessinstid() {
        return processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.PROCESSINSTID
     *
     * @param processinstid the value for T_WFS_OVERTIMEAPPLY_PARENT.PROCESSINSTID
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setProcessinstid(Long processinstid) {
        this.processinstid = processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getApplyPersonId() {
        return applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @param applyPersonId the value for T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setApplyPersonId(String applyPersonId) {
        this.applyPersonId = applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @param applyPersonName the value for T_WFS_OVERTIMEAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.DEPT
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.DEPT
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.DEPT
     *
     * @param dept the value for T_WFS_OVERTIMEAPPLY_PARENT.DEPT
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.POSITION
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.POSITION
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.POSITION
     *
     * @param position the value for T_WFS_OVERTIMEAPPLY_PARENT.POSITION
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.USERID
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.USERID
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.USERID
     *
     * @param userid the value for T_WFS_OVERTIMEAPPLY_PARENT.USERID
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.APPLY_TYPE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.APPLY_TYPE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.APPLY_TYPE
     *
     * @param applyType the value for T_WFS_OVERTIMEAPPLY_PARENT.APPLY_TYPE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.PERSONNEL_DEPT
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.PERSONNEL_DEPT
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getPersonnelDept() {
        return personnelDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.PERSONNEL_DEPT
     *
     * @param personnelDept the value for T_WFS_OVERTIMEAPPLY_PARENT.PERSONNEL_DEPT
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setPersonnelDept(String personnelDept) {
        this.personnelDept = personnelDept;
        this.personnelDeptName = this.personnelDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.OTAPPLYNO
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.OTAPPLYNO
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getOtapplyno() {
        return otapplyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.OTAPPLYNO
     *
     * @param otapplyno the value for T_WFS_OVERTIMEAPPLY_PARENT.OTAPPLYNO
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setOtapplyno(String otapplyno) {
        this.otapplyno = otapplyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.WORKDAYS
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.WORKDAYS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public BigDecimal getWorkdays() {
        return workdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.WORKDAYS
     *
     * @param workdays the value for T_WFS_OVERTIMEAPPLY_PARENT.WORKDAYS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setWorkdays(BigDecimal workdays) {
        this.workdays = workdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.HOLIDAYS
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.HOLIDAYS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public BigDecimal getHolidays() {
        return holidays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.HOLIDAYS
     *
     * @param holidays the value for T_WFS_OVERTIMEAPPLY_PARENT.HOLIDAYS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setHolidays(BigDecimal holidays) {
        this.holidays = holidays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NBEGIN_DATE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.NBEGIN_DATE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public Date getNbeginDate() {
        return nbeginDate;
    }
    
    public String getNbeginDateStr(){
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		return sdf.format(getNbeginDate());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NBEGIN_DATE
     *
     * @param nbeginDate the value for T_WFS_OVERTIMEAPPLY_PARENT.NBEGIN_DATE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setNbeginDate(Date nbeginDate) {
        this.nbeginDate = nbeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NEND_DATE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.NEND_DATE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public Date getNendDate() {
        return nendDate;
    }
    
    public String getNendDateStr(){
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		return sdf.format(getNendDate());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NEND_DATE
     *
     * @param nendDate the value for T_WFS_OVERTIMEAPPLY_PARENT.NEND_DATE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setNendDate(Date nendDate) {
        this.nendDate = nendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NIGHT_DAYS
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.NIGHT_DAYS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public BigDecimal getNightDays() {
        return nightDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NIGHT_DAYS
     *
     * @param nightDays the value for T_WFS_OVERTIMEAPPLY_PARENT.NIGHT_DAYS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setNightDays(BigDecimal nightDays) {
        this.nightDays = nightDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NWITNESS
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.NWITNESS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getNwitness() {
        return nwitness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.NWITNESS
     *
     * @param nwitness the value for T_WFS_OVERTIMEAPPLY_PARENT.NWITNESS
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setNwitness(String nwitness) {
        this.nwitness = nwitness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.OT_INFOMATION
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.OT_INFOMATION
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getOtInfomation() {
        return otInfomation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.OT_INFOMATION
     *
     * @param otInfomation the value for T_WFS_OVERTIMEAPPLY_PARENT.OT_INFOMATION
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setOtInfomation(String otInfomation) {
        this.otInfomation = otInfomation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.REASON
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.REASON
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.REASON
     *
     * @param reason the value for T_WFS_OVERTIMEAPPLY_PARENT.REASON
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.CREATE_TIME
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.CREATE_TIME
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.CREATE_TIME
     *
     * @param createTime the value for T_WFS_OVERTIMEAPPLY_PARENT.CREATE_TIME
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.MODIFY_TIME
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.MODIFY_TIME
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_OVERTIMEAPPLY_PARENT.MODIFY_TIME
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.ISSEFFECTIVE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.ISSEFFECTIVE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_OVERTIMEAPPLY_PARENT.ISSEFFECTIVE
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD1
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD1
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD1
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD2
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD2
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_OVERTIMEAPPLY_PARENT.SPARE_FIELD2
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.SUBNUMBER
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_PARENT.SUBNUMBER
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public BigDecimal getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_PARENT.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_OVERTIMEAPPLY_PARENT.SUBNUMBER
     *
     * @mbggenerated Fri Nov 15 20:08:28 CST 2013
     */
    public void setSubnumber(BigDecimal subnumber) {
        this.subnumber = subnumber;
    }
    public OvertimeApplyParentBean(){}

	/**
	 * @return the overTimeInfoList
	 */
	public List<OvertimeApplyChildBean> getOverTimeInfoList() {
		return overTimeInfoList;
	}

	/**
	 * @param overTimeInfoList the overTimeInfoList to set
	 */
	public void setOverTimeInfoList(List<OvertimeApplyChildBean> overTimeInfoList) {
		this.overTimeInfoList = overTimeInfoList;
	}

	/**
	 * @return the overTimeInfoChild
	 */
	public String getOverTimeInfoChild() {
		return overTimeInfoChild;
	}

	/**
	 * @param overTimeInfoChild the overTimeInfoChild to set
	 */
	public void setOverTimeInfoChild(String overTimeInfoChild) {
		this.overTimeInfoChild = overTimeInfoChild;
	}

	/**
	 * @return the nwitnessId
	 */
	public String getNwitnessId() {
		return nwitnessId;
	}

	/**
	 * @param nwitnessId the nwitnessId to set
	 */
	public void setNwitnessId(String nwitnessId) {
		this.nwitnessId = nwitnessId;
	}

	/**
	 * @return the applyTypeCode
	 */
	public String getApplyTypeCode() {
		return applyTypeCode;
	}

	/**
	 * @param applyTypeCode the applyTypeCode to set
	 */
	public void setApplyTypeCode(String applyTypeCode) {
		this.applyTypeCode = applyTypeCode;
	}

	/**
	 * @return the legaldays
	 */
	public BigDecimal getLegaldays() {
		return legaldays;
	}

	/**
	 * @param legaldays the legaldays to set
	 */
	public void setLegaldays(BigDecimal legaldays) {
		this.legaldays = legaldays;
	}
	/**
	 * 
	* @MethodName: getPersonnelDeptName 
	* @description : TODO
	* @author：liming
	* @date： 2013-12-2 上午11:27:45
	* @return String
	 */
	public String getPersonnelDeptName() {
		return personnelDeptName;
	}
	/**
	 * 
	* @MethodName: setPersonnelDeptName 
	* @description : TODO
	* @author：liming
	* @date： 2013-12-2 上午11:27:49
	* @param personnelDeptName void
	 */
	public void setPersonnelDeptName(String personnelDeptName) {
		this.personnelDeptName = personnelDeptName;
	}
	
}