package com.deppon.wfs.workflow.domain;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
* @title: OvertimeApplyChildBean 
* @description：TODO
* @author： 高雅哲
* @date： 2013-11-15 下午8:13:32
*/

public class OvertimeApplyChildBean extends Entity{
    /**
	* 
	*/
	private static final long serialVersionUID = 1L;

	/**
     *主键
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private String tableid;

    /**
     * 流程序号
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private String busino;

    /**
     * 加班类型
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private String ottype;

    /**
     * 加班开始日期
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private Date beginDate;

    /**
     * 加班结束日期
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private Date endDate;

    /**
     * 创建时间
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private Date createTime;

    /**
     * 修改时间
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private Date modifyTime;

    /**
     * 业务状态
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private String isseffective;

    /**
     * 备用字段1
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private String spareField1;

    /**
     * 备用字段2
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private String spareField2;

    /**
     * 数字字段（扩展）
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    private BigDecimal subnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.TABLEID
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.TABLEID
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.TABLEID
     *
     * @param tableid the value for T_WFS_OVERTIMEAPPLY_CHILD.TABLEID
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setTableid(String tableid) {
        this.tableid = tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.BUSINO
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.BUSINO
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.BUSINO
     *
     * @param busino the value for T_WFS_OVERTIMEAPPLY_CHILD.BUSINO
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.OTTYPE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.OTTYPE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public String getOttype() {
        return ottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.OTTYPE
     *
     * @param ottype the value for T_WFS_OVERTIMEAPPLY_CHILD.OTTYPE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setOttype(String ottype) {
        this.ottype = ottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.BEGIN_DATE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.BEGIN_DATE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public Date getBeginDate() {
        return beginDate;
    }
    
    /**
     * 
    * @MethodName: getBeginDateStr 
    * @description : TODO
    * @author：liming
    * @date： 2013-12-2 下午1:50:40
    * @return String
     */
    public String getBeginDateStr(){
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		return sdf.format(getBeginDate());
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.BEGIN_DATE
     *
     * @param beginDate the value for T_WFS_OVERTIMEAPPLY_CHILD.BEGIN_DATE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.END_DATE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.END_DATE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public Date getEndDate() {
        return endDate;
    }
    
    /**
     * 
    * @MethodName: getEndDateStr 
    * @description : TODO
    * @author：liming
    * @date： 2013-12-2 下午1:52:57
    * @return String
     */
    public String getEndDateStr(){
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		return sdf.format(getEndDate());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.END_DATE
     *
     * @param endDate the value for T_WFS_OVERTIMEAPPLY_CHILD.END_DATE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.CREATE_TIME
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.CREATE_TIME
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.CREATE_TIME
     *
     * @param createTime the value for T_WFS_OVERTIMEAPPLY_CHILD.CREATE_TIME
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.MODIFY_TIME
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.MODIFY_TIME
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_OVERTIMEAPPLY_CHILD.MODIFY_TIME
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.ISSEFFECTIVE
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.ISSEFFECTIVE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_OVERTIMEAPPLY_CHILD.ISSEFFECTIVE
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD1
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD1
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD1
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD2
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD2
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_OVERTIMEAPPLY_CHILD.SPARE_FIELD2
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.SUBNUMBER
     *
     * @return the value of T_WFS_OVERTIMEAPPLY_CHILD.SUBNUMBER
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public BigDecimal getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_OVERTIMEAPPLY_CHILD.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_OVERTIMEAPPLY_CHILD.SUBNUMBER
     *
     * @mbggenerated Fri Nov 15 20:10:40 CST 2013
     */
    public void setSubnumber(BigDecimal subnumber) {
        this.subnumber = subnumber;
    }
    public OvertimeApplyChildBean(){
    	
    }

}