package com.deppon.wfs.workflow.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.deppon.montal.util.FormatUtil;

public class PaymentWageinfoBean {
    /**
     * 流程序号，主键
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String busino;

    /**
     * 流程实例ID
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private Long processinstid;

    /**
     * 申请人员工号
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String applyPersonId;

    /**
     *申请人姓名
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String applyPersonName;

    /**
     * 申请类型
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String applyType;

    /**
     * 申请人所在部门
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String applyDept;

    /**
     *申请时间（老表数据），新表后请参照craete_time
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private Date applydate;

    /**
     *工资年月
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private Date payYearMonth;

    /**
     *更改类型
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String changeType;

    /**
     *申请事由
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String reason;

    /**
     *创建时间
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private Date createTime;

    /**
     * 修改时间
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private Date modifyTime;

    /**
     * 业务状态
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String isseffective;

    /**
     * 备用字段1
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String spareField1;

    /**
     *备用字段2
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private String spareField2;

    /**
     * 数字字段（扩展）
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    private BigDecimal subnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.BUSINO
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.BUSINO
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.BUSINO
     *
     * @param busino the value for T_WFS_PAYMENT_WAGEINFO.BUSINO
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.PROCESSINSTID
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.PROCESSINSTID
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public Long getProcessinstid() {
        return processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.PROCESSINSTID
     *
     * @param processinstid the value for T_WFS_PAYMENT_WAGEINFO.PROCESSINSTID
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setProcessinstid(Long processinstid) {
        this.processinstid = processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_ID
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_ID
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getApplyPersonId() {
        return applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_ID
     *
     * @param applyPersonId the value for T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_ID
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setApplyPersonId(String applyPersonId) {
        this.applyPersonId = applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_NAME
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_NAME
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_NAME
     *
     * @param applyPersonName the value for T_WFS_PAYMENT_WAGEINFO.APPLY_PERSON_NAME
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_TYPE
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.APPLY_TYPE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_TYPE
     *
     * @param applyType the value for T_WFS_PAYMENT_WAGEINFO.APPLY_TYPE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_DEPT
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.APPLY_DEPT
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getApplyDept() {
        return applyDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLY_DEPT
     *
     * @param applyDept the value for T_WFS_PAYMENT_WAGEINFO.APPLY_DEPT
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setApplyDept(String applyDept) {
        this.applyDept = applyDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLYDATE
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.APPLYDATE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public Date getApplydate() {
        return applydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.APPLYDATE
     *
     * @param applydate the value for T_WFS_PAYMENT_WAGEINFO.APPLYDATE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setApplydate(Date applydate) {
        this.applydate = applydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.PAY_YEAR_MONTH
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.PAY_YEAR_MONTH
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public Date getPayYearMonth() {
        return payYearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.PAY_YEAR_MONTH
     *
     * @param payYearMonth the value for T_WFS_PAYMENT_WAGEINFO.PAY_YEAR_MONTH
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setPayYearMonth(Date payYearMonth) {
        this.payYearMonth = payYearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.CHANGE_TYPE
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.CHANGE_TYPE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.CHANGE_TYPE
     *
     * @param changeType the value for T_WFS_PAYMENT_WAGEINFO.CHANGE_TYPE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.REASON
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.REASON
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.REASON
     *
     * @param reason the value for T_WFS_PAYMENT_WAGEINFO.REASON
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.CREATE_TIME
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.CREATE_TIME
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.CREATE_TIME
     *
     * @param createTime the value for T_WFS_PAYMENT_WAGEINFO.CREATE_TIME
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.MODIFY_TIME
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.MODIFY_TIME
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_PAYMENT_WAGEINFO.MODIFY_TIME
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.ISSEFFECTIVE
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.ISSEFFECTIVE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_PAYMENT_WAGEINFO.ISSEFFECTIVE
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD1
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD1
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD1
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD2
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD2
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_PAYMENT_WAGEINFO.SPARE_FIELD2
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_PAYMENT_WAGEINFO.SUBNUMBER
     *
     * @return the value of T_WFS_PAYMENT_WAGEINFO.SUBNUMBER
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public BigDecimal getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_PAYMENT_WAGEINFO.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_PAYMENT_WAGEINFO.SUBNUMBER
     *
     * @mbggenerated Mon Nov 11 11:54:01 CST 2013
     */
    public void setSubnumber(BigDecimal subnumber) {
        this.subnumber = subnumber;
    }
}