package com.deppon.wfs.workflow.domain;

import java.util.Date;

/**
* @title: PostApplicationBean 
* @description：新增岗位申请实体类
* @author： 关波
* @date： 2014-5-21 下午3:46:03
*/
public class PostApplyBean extends Entity{
    /**
	* 
	*/
	private static final long serialVersionUID = 1L;

	/** 主键 **/
    private String busino;

	/** 流程实例ID **/
    private Long processinstid;
    
    /** 申请人工号 **/
    private String applyPersonId;

    /** 申请人姓名 **/
    private String applyPersonName;

    /** 新增岗位名称 **/
    private String postName;

    /** 申请事由 **/
    private String applyReasons;

    /** 创建时间 **/
    private Date createTime;

    /** 修改时间 **/
    private Date modifyTime;

    /** 业务状态 **/
    private String isseffective;

    /** 备用字段1 **/
    private Object spareField1;

    /** 备用字段2 **/
    private Object spareField2;

    /** 数字型备用字段 **/
    private Long subnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.BUSINO
     *
     * @return the value of T_WFS_POSTAPPLICATION.BUSINO
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.BUSINO
     *
     * @param busino the value for T_WFS_POSTAPPLICATION.BUSINO
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.PROCESSINSTID
     *
     * @return the value of T_WFS_POSTAPPLICATION.PROCESSINSTID
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public Long getProcessinstid() {
        return processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.PROCESSINSTID
     *
     * @param processinstid the value for T_WFS_POSTAPPLICATION.PROCESSINSTID
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setProcessinstid(Long processinstid) {
        this.processinstid = processinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.APPLYPERSONID
     *
     * @return the value of T_WFS_POSTAPPLICATION.APPLYPERSONID
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public String getApplyPersonId() {
		return applyPersonId;
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.APPLYPERSONID
     *
     * @param empname the value for T_WFS_POSTAPPLICATION.APPLYPERSONID
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
	public void setApplyPersonId(String applyPersonId) {
		this.applyPersonId = applyPersonId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.APPLYPERSONNAME
     *
     * @return the value of T_WFS_POSTAPPLICATION.APPLYPERSONNAME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.APPLYPERSONNAME
     *
     * @param empname the value for T_WFS_POSTAPPLICATION.APPLYPERSONNAME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.POST_NAME
     *
     * @return the value of T_WFS_POSTAPPLICATION.POST_NAME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.POST_NAME
     *
     * @param postName the value for T_WFS_POSTAPPLICATION.POST_NAME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.APPLY_REASONS
     *
     * @return the value of T_WFS_POSTAPPLICATION.APPLY_REASONS
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public String getApplyReasons() {
        return applyReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.APPLY_REASONS
     *
     * @param applyReasons the value for T_WFS_POSTAPPLICATION.APPLY_REASONS
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setApplyReasons(String applyReasons) {
        this.applyReasons = applyReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.CREATE_TIME
     *
     * @return the value of T_WFS_POSTAPPLICATION.CREATE_TIME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.CREATE_TIME
     *
     * @param createTime the value for T_WFS_POSTAPPLICATION.CREATE_TIME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.MODIFY_TIME
     *
     * @return the value of T_WFS_POSTAPPLICATION.MODIFY_TIME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_POSTAPPLICATION.MODIFY_TIME
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.ISSEFFECTIVE
     *
     * @return the value of T_WFS_POSTAPPLICATION.ISSEFFECTIVE
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_POSTAPPLICATION.ISSEFFECTIVE
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.SPARE_FIELD1
     *
     * @return the value of T_WFS_POSTAPPLICATION.SPARE_FIELD1
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public Object getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_POSTAPPLICATION.SPARE_FIELD1
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setSpareField1(Object spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.SPARE_FIELD2
     *
     * @return the value of T_WFS_POSTAPPLICATION.SPARE_FIELD2
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public Object getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_POSTAPPLICATION.SPARE_FIELD2
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setSpareField2(Object spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_POSTAPPLICATION.SUBNUMBER
     *
     * @return the value of T_WFS_POSTAPPLICATION.SUBNUMBER
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public Long getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_POSTAPPLICATION.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_POSTAPPLICATION.SUBNUMBER
     *
     * @mbggenerated Sat Oct 12 14:39:42 CST 2013
     */
    public void setSubnumber(Long subnumber) {
        this.subnumber = subnumber;
    }
}