package com.deppon.wfs.workflow.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class SystempowerapplyParentBean extends Entity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 存放申请明细
	 */
	private List<SystempowerapplyChildBean> sysApplyDetailedList;
	/** 
	 * 存放申请明细的json字符串
	 */
	private String sysApplyDetailed;
	/**
     * 流程序号，主键
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String busino;

    /**
     * 流程实例ID
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private Long processinstid;

    /**
     * 申请人员工号
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String applyPersonId;

    /**
     * 申请人姓名
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String applyPersonName;

    /**
     * 申请人所属部门
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String empdept;

    /**
     * 申请人职位
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String empposition;

    /**
     * 申请权限（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String powertype;

    /**
     * 使用人（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String username;

    /**
     * 使用人工号（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String userid;

    /**
     * 使用人入职日期（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private Date entrydate;

    /**
     * 使用人职位（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String userposition;

    /**
     *权限截止日期（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private Date endtime;

    /**
     *申请类型（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String applytype;

    /**
     * 固定资产编码（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String fixedassetcode;

    /**
     * 主机是否需要认证（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String iscertification;

    /**
     *负责子公司（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String subcom;

    /**
     * 异动前部门（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String beforedept;

    /**
     * 异动前岗位（老表）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String beforeposition;
    /**
     * 审批用：是否需要专业部门审批
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String isneedProfessional;
    /**
     * 审批用：选择的审批人姓名
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String professionalName;
    /**
     * 审批用：选择的审批人工号
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String professionalNameCode;
    /**
     * 审批用：选择的审批部门
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String professionalDept;
    /**
     * 审批用：选择的审批部门编码
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String professionalDeptCode;
    /**
     * 审批用：权限异常系统
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String powerErrorSys;
    /**
     * 审批用：权限异常系统对应业务字典编码
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String powerErrorSysCode;
    /**
     * 审批用：无值代表没有异常   ‘1’代表有异常
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String sysError;
    /**
     * 申请事由
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String whyapply;

    /**
     * 创建时间
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private Date createTime;

    /**
     * 修改时间
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private Date modifyTime;

    /**
     * 业务状态
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String isseffective;

    /**
     * 备用字段1
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String spareField1;

    /**
     * 备用字段2
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private String spareField2;

    /**
     * 数字字段（扩展）
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    private BigDecimal subnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.BUSINO
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.BUSINO
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getBusino() {
        return busino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.BUSINO
     *
     * @param busino the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.BUSINO
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setBusino(String busino) {
        this.busino = busino;
    }

  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getApplyPersonId() {
        return applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @param applyPersonId the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_ID
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setApplyPersonId(String applyPersonId) {
        this.applyPersonId = applyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getApplyPersonName() {
        return applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @param applyPersonName the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLY_PERSON_NAME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setApplyPersonName(String applyPersonName) {
        this.applyPersonName = applyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPDEPT
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPDEPT
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getEmpdept() {
        return empdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPDEPT
     *
     * @param empdept the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPDEPT
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setEmpdept(String empdept) {
        this.empdept = empdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPPOSITION
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPPOSITION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getEmpposition() {
        return empposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPPOSITION
     *
     * @param empposition the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.EMPPOSITION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setEmpposition(String empposition) {
        this.empposition = empposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.POWERTYPE
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.POWERTYPE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getPowertype() {
        return powertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.POWERTYPE
     *
     * @param powertype the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.POWERTYPE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setPowertype(String powertype) {
        this.powertype = powertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.USERNAME
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.USERNAME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.USERNAME
     *
     * @param username the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.USERNAME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.USERID
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.USERID
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.USERID
     *
     * @param userid the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.USERID
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ENTRYDATE
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.ENTRYDATE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ENTRYDATE
     *
     * @param entrydate the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.ENTRYDATE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.USERPOSITION
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.USERPOSITION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getUserposition() {
        return userposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.USERPOSITION
     *
     * @param userposition the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.USERPOSITION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setUserposition(String userposition) {
        this.userposition = userposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ENDTIME
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.ENDTIME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ENDTIME
     *
     * @param endtime the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.ENDTIME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLYTYPE
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLYTYPE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getApplytype() {
        return applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLYTYPE
     *
     * @param applytype the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.APPLYTYPE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setApplytype(String applytype) {
        this.applytype = applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.FIXEDASSETCODE
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.FIXEDASSETCODE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getFixedassetcode() {
        return fixedassetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.FIXEDASSETCODE
     *
     * @param fixedassetcode the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.FIXEDASSETCODE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setFixedassetcode(String fixedassetcode) {
        this.fixedassetcode = fixedassetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ISCERTIFICATION
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.ISCERTIFICATION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getIscertification() {
        return iscertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ISCERTIFICATION
     *
     * @param iscertification the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.ISCERTIFICATION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setIscertification(String iscertification) {
        this.iscertification = iscertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBCOM
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBCOM
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getSubcom() {
        return subcom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBCOM
     *
     * @param subcom the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBCOM
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setSubcom(String subcom) {
        this.subcom = subcom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREDEPT
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREDEPT
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getBeforedept() {
        return beforedept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREDEPT
     *
     * @param beforedept the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREDEPT
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setBeforedept(String beforedept) {
        this.beforedept = beforedept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREPOSITION
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREPOSITION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getBeforeposition() {
        return beforeposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREPOSITION
     *
     * @param beforeposition the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.BEFOREPOSITION
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setBeforeposition(String beforeposition) {
        this.beforeposition = beforeposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.WHYAPPLY
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.WHYAPPLY
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getWhyapply() {
        return whyapply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.WHYAPPLY
     *
     * @param whyapply the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.WHYAPPLY
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setWhyapply(String whyapply) {
        this.whyapply = whyapply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.CREATE_TIME
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.CREATE_TIME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.CREATE_TIME
     *
     * @param createTime the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.CREATE_TIME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.MODIFY_TIME
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.MODIFY_TIME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.MODIFY_TIME
     *
     * @param modifyTime the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.MODIFY_TIME
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ISSEFFECTIVE
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.ISSEFFECTIVE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getIsseffective() {
        return isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.ISSEFFECTIVE
     *
     * @param isseffective the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.ISSEFFECTIVE
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setIsseffective(String isseffective) {
        this.isseffective = isseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD1
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD1
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD1
     *
     * @param spareField1 the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD1
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD2
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD2
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD2
     *
     * @param spareField2 the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.SPARE_FIELD2
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBNUMBER
     *
     * @return the value of T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBNUMBER
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public BigDecimal getSubnumber() {
        return subnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBNUMBER
     *
     * @param subnumber the value for T_WFS_SYSTEMPOWERAPPLY_PARENT.SUBNUMBER
     *
     * @mbggenerated Mon Jan 13 22:44:42 CST 2014
     */
    public void setSubnumber(BigDecimal subnumber) {
        this.subnumber = subnumber;
    }
    public SystempowerapplyParentBean(){}

	/**
	 * @return the sysApplyDetailedList
	 */
	public List<SystempowerapplyChildBean> getSysApplyDetailedList() {
		return sysApplyDetailedList;
	}

	/**
	 * @param sysApplyDetailedList the sysApplyDetailedList to set
	 */
	public void setSysApplyDetailedList(
			List<SystempowerapplyChildBean> sysApplyDetailedList) {
		this.sysApplyDetailedList = sysApplyDetailedList;
	}

	/**
	 * @return the sysApplyDetailed
	 */
	public String getSysApplyDetailed() {
		return sysApplyDetailed;
	}

	/**
	 * @param sysApplyDetailed the sysApplyDetailed to set
	 */
	public void setSysApplyDetailed(String sysApplyDetailed) {
		this.sysApplyDetailed = sysApplyDetailed;
	}

	/**
	 * @return the processinstid
	 */
	public Long getProcessinstid() {
		return processinstid;
	}

	/**
	 * @param processinstid the processinstid to set
	 */
	public void setProcessinstid(Long processinstid) {
		this.processinstid = processinstid;
	}

	/**
	 * @return the isneedProfessional
	 */
	public String getIsneedProfessional() {
		return isneedProfessional;
	}

	/**
	 * @param isneedProfessional the isneedProfessional to set
	 */
	public void setIsneedProfessional(String isneedProfessional) {
		this.isneedProfessional = isneedProfessional;
	}

	/**
	 * @return the professionalName
	 */
	public String getProfessionalName() {
		return professionalName;
	}

	/**
	 * @param professionalName the professionalName to set
	 */
	public void setProfessionalName(String professionalName) {
		this.professionalName = professionalName;
	}

	/**
	 * @return the professionalNameCode
	 */
	public String getProfessionalNameCode() {
		return professionalNameCode;
	}

	/**
	 * @param professionalNameCode the professionalNameCode to set
	 */
	public void setProfessionalNameCode(String professionalNameCode) {
		this.professionalNameCode = professionalNameCode;
	}

	/**
	 * @return the professionalDept
	 */
	public String getProfessionalDept() {
		return professionalDept;
	}

	/**
	 * @param professionalDept the professionalDept to set
	 */
	public void setProfessionalDept(String professionalDept) {
		this.professionalDept = professionalDept;
	}

	/**
	 * @return the professionalDeptCode
	 */
	public String getProfessionalDeptCode() {
		return professionalDeptCode;
	}

	/**
	 * @param professionalDeptCode the professionalDeptCode to set
	 */
	public void setProfessionalDeptCode(String professionalDeptCode) {
		this.professionalDeptCode = professionalDeptCode;
	}

	/**
	 * @return the powerErrorSys
	 */
	public String getPowerErrorSys() {
		return powerErrorSys;
	}

	/**
	 * @param powerErrorSys the powerErrorSys to set
	 */
	public void setPowerErrorSys(String powerErrorSys) {
		this.powerErrorSys = powerErrorSys;
	}

	/**
	 * @return the powerErrorSysCode
	 */
	public String getPowerErrorSysCode() {
		return powerErrorSysCode;
	}

	/**
	 * @param powerErrorSysCode the powerErrorSysCode to set
	 */
	public void setPowerErrorSysCode(String powerErrorSysCode) {
		this.powerErrorSysCode = powerErrorSysCode;
	}

	/**
	 * @return the sysError
	 */
	public String getSysError() {
		return sysError;
	}

	/**
	 * @param sysError the sysError to set
	 */
	public void setSysError(String sysError) {
		this.sysError = sysError;
	}
}