package com.deppon.wdgh.inteface.domain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.7
 * 2014-06-30T14:56:17.765+08:00
 * Generated source version: 2.6.7
 * 
 */
@WebService(targetNamespace = "http://www.deppon.com/wdgh/inteface/domain/", name = "IDpmToWdghService")
@XmlSeeAlso({com.deppon.esb.header.ObjectFactory.class, com.deppon.esb.exception.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IDpmToWdghService {

    @WebResult(name = "workflowApproveResponse", targetNamespace = "http://www.deppon.com/wdgh/inteface/domain/", partName = "response")
    @WebMethod(action = "http://www.deppon.com/wdgh/interface/WdghService/workflowApprove")
    public WorkflowApproveResponse workflowApprove(
        @WebParam(partName = "request", name = "workflowApproveRequest", targetNamespace = "http://www.deppon.com/wdgh/inteface/domain/")
        WorkflowApproveRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommException;

    @WebResult(name = "queryWorkflowInfoResponse", targetNamespace = "http://www.deppon.com/wdgh/inteface/domain/", partName = "response")
    @WebMethod(action = "http://www.deppon.com/wdgh/interface/WdghService/queryWorkflowInfo")
    public QueryWorkflowInfoResponse queryWorkflowInfo(
        @WebParam(partName = "request", name = "queryWorkflowInfoRequest", targetNamespace = "http://www.deppon.com/wdgh/inteface/domain/")
        QueryWorkflowInfoRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommException;
}
