package com.deppon.wdgh.inteface.domain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.7
 * 2014-06-30T14:56:17.812+08:00
 * Generated source version: 2.6.7
 * 
 */
@WebServiceClient(name = "WdghService", 
                  wsdlLocation = "http://192.168.67.12:8580/esb2/ws/dpm2wdgh/queryWorkflow?wsdl",
                  targetNamespace = "http://www.deppon.com/wdgh/inteface/domain/") 
public class WdghService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.deppon.com/wdgh/inteface/domain/", "WdghService");
    public final static QName DpmToWdghSOAP = new QName("http://www.deppon.com/wdgh/inteface/domain/", "dpmToWdghSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.67.12:8580/esb2/ws/dpm2wdgh/queryWorkflow?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WdghService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.67.12:8580/esb2/ws/dpm2wdgh/queryWorkflow?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WdghService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WdghService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WdghService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
   /* public WdghService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }*/

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    /*public WdghService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }*/

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    /*public WdghService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     *
     * @return
     *     returns IDpmToWdghService
     */
    @WebEndpoint(name = "dpmToWdghSOAP")
    public IDpmToWdghService getDpmToWdghSOAP() {
        return super.getPort(DpmToWdghSOAP, IDpmToWdghService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDpmToWdghService
     */
    @WebEndpoint(name = "dpmToWdghSOAP")
    public IDpmToWdghService getDpmToWdghSOAP(WebServiceFeature... features) {
        return super.getPort(DpmToWdghSOAP, IDpmToWdghService.class, features);
    }

}
