
/*
 * 
 */

package com.deppon.dpm.webservice.dpmtoappservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Jun 30 16:47:37 CST 2014
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "DpmToAppService", 
                  wsdlLocation = "file:/F:/wfs_workspace/createWebServiceServer/src/main/resources/DpmToAppService.wsdl",
                  targetNamespace = "http://www.deppon.com/dpm/webService/DpmToAppService") 
public class DpmToAppService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.deppon.com/dpm/webService/DpmToAppService", "DpmToAppService");
    public final static QName DpmToAppService = new QName("http://www.deppon.com/dpm/webService/DpmToAppService", "DpmToAppService");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/wfs_workspace/createWebServiceServer/src/main/resources/DpmToAppService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/F:/wfs_workspace/createWebServiceServer/src/main/resources/DpmToAppService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DpmToAppService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DpmToAppService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DpmToAppService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns DpmToAppService
     */
    @WebEndpoint(name = "DpmToAppService")
    public DpmToAppService getDpmToAppService() {
        return super.getPort(DpmToAppService, DpmToAppService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DpmToAppService
     */
    @WebEndpoint(name = "DpmToAppService")
    public DpmToAppService getDpmToAppService(WebServiceFeature... features) {
        return super.getPort(DpmToAppService, DpmToAppService.class, features);
    }

}
