
/*
 * 
 */

package com.deppon.montal.module.crm.serivce;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Apr 18 09:07:11 CST 2014
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "CrmService", 
                  wsdlLocation = "file:/E:/workspace/test/src/main/resources/fssc4oa/CrmService.wsdl",
                  targetNamespace = "http://www.deppon.com/crm/interface/CrmService") 
public class CrmService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.deppon.com/crm/interface/CrmService", "CrmService");
    public final static QName CrmService = new QName("http://www.deppon.com/crm/interface/CrmService", "CrmService");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/workspace/test/src/main/resources/fssc4oa/CrmService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/E:/workspace/test/src/main/resources/fssc4oa/CrmService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CrmService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CrmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrmService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IDpmToCrmService
     */
    @WebEndpoint(name = "CrmService")
    public IDpmToCrmService getCrmService() {
        return super.getPort(CrmService, IDpmToCrmService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDpmToCrmService
     */
    @WebEndpoint(name = "CrmService")
    public IDpmToCrmService getCrmService(WebServiceFeature... features) {
        return super.getPort(CrmService, IDpmToCrmService.class, features);
    }

}
