package com.deppon.montal.module.crm.serivce;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Apr 18 09:07:11 CST 2014
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://www.deppon.com/crm/interface/CrmService", name = "IDpmToCrmService")
@XmlSeeAlso({com.deppon.montal.module.crm.damin.ObjectFactory.class,com.deppon.esb.header.ObjectFactory.class,com.deppon.esb.exception.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IDpmToCrmService {

    @WebResult(name = "workflowApproveResponse", targetNamespace = "http://www.deppon.com/crm/inteface/dpm/domain/", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/workflowApprove")
    public com.deppon.montal.module.crm.damin.WorkflowApproveResponse workflowApprove(
        @WebParam(partName = "request", name = "workflowApproveRequest", targetNamespace = "http://www.deppon.com/crm/inteface/dpm/domain/")
        com.deppon.montal.module.crm.damin.WorkflowApproveRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommException;

    @WebResult(name = "queryWorkflowInfoResponse", targetNamespace = "http://www.deppon.com/crm/inteface/dpm/domain/", partName = "response")
    @WebMethod(action = "http://www.deppon.com/crm/interface/CrmService/queryWorkflowInfo")
    public com.deppon.montal.module.crm.damin.QueryWorkflowInfoResponse queryWorkflowInfo(
        @WebParam(partName = "request", name = "queryWorkflowInfoRequest", targetNamespace = "http://www.deppon.com/crm/inteface/dpm/domain/")
        com.deppon.montal.module.crm.damin.QueryWorkflowInfoRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommException;
}
