CREATE TABLE DIDI_ORDER (
   ID int(11) NOT NULL AUTO_INCREMENT,
   BILLNO varchar(100) ,
   NAME varchar(20) ,
   EMPLOYEENO varchar(50) ,
   MODELS varchar(50) ,
   FROM_NAME varchar(500) ,
   TO_NAME varchar(500) ,
   TAXIDATE  varchar(20) ,
   BOARDINGTIME varchar(20) ,
   OFFTIME varchar(10) ,
   ORDERSTATUS int ,
   SUB_STATUS int ,
   NORMAL_DISTANCE varchar(100) ,
   TOTAL_PRICE varchar(100) ,
   DEPT varchar(100) ,
   FINANCEDEPT varchar(100) ,
   BUDGETRATIO varchar(100) ,
   TIMESCHEDULE varchar(100) ,
   REMARK varchar(100) ,
   REMARKINFO varchar(500) ,
   COMPANY varchar(100) ,
   PRIMARY KEY (ID)
);
