package com.deppon.lsp.module.mobilesecondworkflowlist.controlcenter.server.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jun 13 10:20:53 CST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.deppon.com/lsp/module/mobilesecondworkflowlist/controlcenter/server/service", name = "IMobileSecondWorkflowService")
@XmlSeeAlso({com.deppon.esb.header.ObjectFactory.class,ObjectFactory.class,com.deppon.esb.exception.ObjectFactory.class,com.deppon.lsp.module.mobilesecondworkflowlist.controlcenter.shared.domain.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IMobileSecondWorkflowService {

    @WebResult(name = "WorkflowBusinessDataResponse", targetNamespace = "http://www.deppon.com/lsp/module/mobilesecondworkflowlist/controlcenter/shared/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/lsp/interface/LspSecondService/queryWorkflowInfo")
    public com.deppon.lsp.module.mobilesecondworkflowlist.controlcenter.shared.domain.WorkflowSecondEntity queryWorkflowInfo(
        @WebParam(partName = "request", name = "WorkflowBusinessData", targetNamespace = "http://www.deppon.com/lsp/module/mobilesecondworkflowlist/controlcenter/shared/domain")
        com.deppon.lsp.module.mobilesecondworkflowlist.controlcenter.shared.domain.WorkflowBusinessData request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommException;

    @WebResult(name = "auditOperationInLspResponse", targetNamespace = "http://www.deppon.com/lsp/module/mobilesecondworkflowlist/controlcenter/shared/domain", partName = "response")
    @WebMethod(action = "http://www.deppon.com/lsp/interface/LspSecondService/workflowApprove")
    public int workflowApprove(
        @WebParam(partName = "request", name = "auditOperationInLsp", targetNamespace = "http://www.deppon.com/lsp/module/mobilesecondworkflowlist/controlcenter/shared/domain")
        com.deppon.lsp.module.mobilesecondworkflowlist.controlcenter.shared.domain.Auditparameters request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommException;
}
