//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 08:43:10 上午 CST 
//


package com.deppon.foss.module.sync.business.jms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deppon.foss.module.sync.business.jms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SyncEmployeeRequest_QNAME = new QName("http://www.deppon.com/wdgh/inteface/domain/", "syncEmployeeRequest");
    private final static QName _SendEmployeeResponse_QNAME = new QName("http://www.deppon.com/wdgh/inteface/domain/", "sendEmployeeResponse");
    private final static QName _SyncAdminOrgRequest_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SyncAdminOrgRequest");
    private final static QName _SyncAdminOrgResponse_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/usermanagement", "SyncAdminOrgResponse");
    /* 配合主项目接口改造，add by 150953[fengshijie] at 2015/03/25 */
    private final static QName _SendMdmEmpRequest_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/employee", "SendMdmEmpRequest");
    private final static QName _SendMdmEmpResponse_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/employee", "SendMdmEmpResponse");

    private final static QName _SendMdmOrgRequest_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/dept", "SendMdmOrgRequest");
    private final static QName _SendMdmOrgResponse_QNAME = new QName("http://www.deppon.com/uums/inteface/domain/dept", "SendMdmOrgResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deppon.foss.module.sync.business.jms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SyncAdminOrgResponse }
     * 
     */
    public SyncAdminOrgResponse createSyncAdminOrgResponse() {
        return new SyncAdminOrgResponse();
    }

    /**
     * Create an instance of {@link SyncAdminOrgProcessReult }
     * 
     */
    public SyncAdminOrgProcessReult createSyncAdminOrgProcessReult() {
        return new SyncAdminOrgProcessReult();
    }

    /**
     * Create an instance of {@link AdminOrgInfo }
     * 
     */
    public AdminOrgInfo createAdminOrgInfo() {
        return new AdminOrgInfo();
    }

    /**
     * Create an instance of {@link SyncAdminOrgRequest }
     * 
     */
    public SyncAdminOrgRequest createSyncAdminOrgRequest() {
        return new SyncAdminOrgRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncAdminOrgRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SyncAdminOrgRequest")
    public JAXBElement<SyncAdminOrgRequest> createSyncAdminOrgRequest(SyncAdminOrgRequest value) {
        return new JAXBElement<SyncAdminOrgRequest>(_SyncAdminOrgRequest_QNAME, SyncAdminOrgRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncAdminOrgResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", name = "SyncAdminOrgResponse")
    public JAXBElement<SyncAdminOrgResponse> createSyncAdminOrgResponse(SyncAdminOrgResponse value) {
        return new JAXBElement<SyncAdminOrgResponse>(_SyncAdminOrgResponse_QNAME, SyncAdminOrgResponse.class, null, value);
    }

    /**
     * Create an instance of {@link SendEmployeeResponse }
     * 
     */
    public SendEmployeeResponse createSendEmployeeResponse() {
        return new SendEmployeeResponse();
    }

    /**
     * Create an instance of {@link SyncEmployeeRequest }
     * 
     */
    public SyncEmployeeRequest createSyncEmployeeRequest() {
        return new SyncEmployeeRequest();
    }

    /**
     * Create an instance of {@link SendEmployeeProcessReult }
     * 
     */
    public SendEmployeeProcessReult createSendEmployeeProcessReult() {
        return new SendEmployeeProcessReult();
    }

    /**
     * Create an instance of {@link EmployeeInfo }
     * 
     */
    public EmployeeInfo createEmployeeInfo() {
        return new EmployeeInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncEmployeeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/wdgh/inteface/domain/", name = "syncEmployeeRequest")
    public JAXBElement<SyncEmployeeRequest> createSyncEmployeeRequest(SyncEmployeeRequest value) {
        return new JAXBElement<SyncEmployeeRequest>(_SyncEmployeeRequest_QNAME, SyncEmployeeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/wdgh/inteface/domain/", name = "sendEmployeeResponse")
    public JAXBElement<SendEmployeeResponse> createSendEmployeeResponse(SendEmployeeResponse value) {
        return new JAXBElement<SendEmployeeResponse>(_SendEmployeeResponse_QNAME, SendEmployeeResponse.class, null, value);
    }
    
    /**
     * <p>Create an instance of {@link JAXBElement }{@code <}{@link SendMdmEmpRequest }{@code >}}</p> 
     * 人员-request
     * @author 150953 冯世杰
     * @date 2015-3-25 下午4:00:41
     * @param value
     * @return
     * @see
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/employee", name = "SendMdmEmpRequest")
    public JAXBElement<SendMdmEmpRequest> createSendMdmEmpRequest(SendMdmEmpRequest value) {
        return new JAXBElement<SendMdmEmpRequest>(_SendMdmEmpRequest_QNAME, SendMdmEmpRequest.class, null, value);
    }
    /**
     * <p>人员-response</p> 
     * @author 150953 冯世杰
     * @date 2015-3-25 下午7:39:11
     * @param value
     * @return
     * @see
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/employee", name = "SendMdmEmpResponse")
    public JAXBElement<SendMdmEmpResponse> createSendMdmEmpResponse(SendMdmEmpResponse value) {
        return new JAXBElement<SendMdmEmpResponse>(_SendMdmEmpResponse_QNAME, SendMdmEmpResponse.class, null, value);
    }
    /**
     * <p>部门-request</p> 
     * @author 150953 冯世杰
     * @date 2015-3-25 下午7:42:29
     * @param value
     * @return
     * @see
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/dept", name = "SendMdmOrgRequest")
    public JAXBElement<SendMdmOrgRequest> createSendMdmOrgRequest(SendMdmOrgRequest value) {
        return new JAXBElement<SendMdmOrgRequest>(_SendMdmOrgRequest_QNAME, SendMdmOrgRequest.class, null, value);
    }
    /**
     * <p>部门-response</p> 
     * @author 150953 冯世杰
     * @date 2015-3-25 下午7:42:39
     * @param value
     * @return
     * @see
     */
    @XmlElementDecl(namespace = "http://www.deppon.com/uums/inteface/domain/dept", name = "SendMdmOrgRequest")
    public JAXBElement<SendMdmOrgResponse> createSendMdmOrgResponse(SendMdmOrgResponse value) {
        return new JAXBElement<SendMdmOrgResponse>(_SendMdmOrgResponse_QNAME, SendMdmOrgResponse.class, null, value);
    }
    
    
}
