//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 08:31:08 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", 
										elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.deppon.foss.module.sync.business.jms;

