package com.deppon.dpm.module.projecttools.shared.domain;

import com.deppon.foss.framework.entity.BaseEntity;

/**
 * 
 * 项目范围（业务范围）
 * @author 150970
 * @date 2015年1月5日 下午12:14:26
 * @since
 * @version
 */
public class ProjectScopeBusinessEntity extends BaseEntity {
	/**
	 * 序列化ID
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_business.biz_id
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    private Integer bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_business.project_code
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_business.biz_module
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    private String bizModule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_business.biz_content
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    private String bizContent2;
    
    
    private String projectCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_business.biz_module
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    private String bizModule2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_business.biz_content
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    private String bizContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_business.biz_id
     *
     * @return the value of dotp_pm_project_scope_business.biz_id
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public Integer getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_business.biz_id
     *
     * @param bizId the value for dotp_pm_project_scope_business.biz_id
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public void setBizId(Integer bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_business.project_code
     *
     * @return the value of dotp_pm_project_scope_business.project_code
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_business.project_code
     *
     * @param projectCode the value for dotp_pm_project_scope_business.project_code
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_business.biz_module
     *
     * @return the value of dotp_pm_project_scope_business.biz_module
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public String getBizModule() {
        return bizModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_business.biz_module
     *
     * @param bizModule the value for dotp_pm_project_scope_business.biz_module
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public void setBizModule(String bizModule) {
        this.bizModule = bizModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_business.biz_content
     *
     * @return the value of dotp_pm_project_scope_business.biz_content
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public String getBizContent() {
        return bizContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_business.biz_content
     *
     * @param bizContent the value for dotp_pm_project_scope_business.biz_content
     *
     * @mbggenerated Thu Nov 13 22:42:50 CST 2014
     */
    public void setBizContent(String bizContent) {
        this.bizContent = bizContent;
    }

	/**
	 * @return  the bizContent2
	 */
	public String getBizContent2() {
		return bizContent2;
	}

	/**
	 * @param bizContent2 the bizContent2 to set
	 */
	public void setBizContent2(String bizContent2) {
		this.bizContent2 = bizContent2;
	}

	/**
	 * @return  the projectCode2
	 */
	public String getProjectCode2() {
		return projectCode2;
	}

	/**
	 * @param projectCode2 the projectCode2 to set
	 */
	public void setProjectCode2(String projectCode2) {
		this.projectCode2 = projectCode2;
	}

	/**
	 * @return  the bizModule2
	 */
	public String getBizModule2() {
		return bizModule2;
	}

	/**
	 * @param bizModule2 the bizModule2 to set
	 */
	public void setBizModule2(String bizModule2) {
		this.bizModule2 = bizModule2;
	}
    
}