package com.deppon.dpm.module.projecttools.shared.domain;

import com.deppon.foss.framework.entity.BaseEntity;

/**
 * 
 * 项目范围（涉及部门）
 * @author 150970
 * @date 2015年1月5日 下午12:14:01
 * @since
 * @version
 */
public class ProjectScopeDeptEntity extends BaseEntity {
	/**
	 * 序列化ID
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_dept.AI_ID
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    private Integer aiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_dept.project_code
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_dept.dept_bcode
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    private String deptBcode;
    /**
     * 部门名称
     */
    private String deptName;
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_dept.AI_ID
     *
     * @return the value of dotp_pm_project_scope_dept.AI_ID
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    public Integer getAiId() {
        return aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_dept.AI_ID
     *
     * @param aiId the value for dotp_pm_project_scope_dept.AI_ID
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    public void setAiId(Integer aiId) {
        this.aiId = aiId;
    }

    /**
	 * @return the deptName
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * @param deptName
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_dept.project_code
     *
     * @return the value of dotp_pm_project_scope_dept.project_code
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_dept.project_code
     *
     * @param projectCode the value for dotp_pm_project_scope_dept.project_code
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_dept.dept_bcode
     *
     * @return the value of dotp_pm_project_scope_dept.dept_bcode
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    public String getDeptBcode() {
        return deptBcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_dept.dept_bcode
     *
     * @param deptBcode the value for dotp_pm_project_scope_dept.dept_bcode
     *
     * @mbggenerated Thu Nov 13 22:45:54 CST 2014
     */
    public void setDeptBcode(String deptBcode) {
        this.deptBcode = deptBcode;
    }

	/** 
	 * <p>重写hashCode方法</p> 
	 * @author 150970
	 * @date 2015年1月5日 下午12:13:20
	 * @return 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result
				+ ((deptBcode == null) ? 0 : deptBcode.hashCode());
		result = prime * result
				+ ((projectCode == null) ? 0 : projectCode.hashCode());
		return result;
	}

	/** 
	 * <p>重写equals方法</p> 
	 * @author 150970
	 * @date 2015年1月5日 下午12:13:20
	 * @param obj
	 * @return 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProjectScopeDeptEntity other = (ProjectScopeDeptEntity) obj;
		if (deptBcode == null) {
			if (other.deptBcode != null)
				return false;
		} else if (!deptBcode.equals(other.deptBcode))
			return false;
		if (projectCode == null) {
			if (other.projectCode != null)
				return false;
		} else if (!projectCode.equals(other.projectCode))
			return false;
		return true;
	}
}