package com.deppon.dpm.module.projecttools.shared.domain;

import com.deppon.foss.framework.entity.BaseEntity;

/**
 * 
 * 项目范围（系统范围）
 * @author 150970
 * @date 2015年1月5日 下午12:15:09
 * @since
 * @version
 */
public class ProjectScopeSysEntity extends BaseEntity {
	/**
	 * 序列化ID
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.AI_ID
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private Integer aiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.project_code
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.sys_code
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private String sysCode;
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.is_main
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private Integer isMain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.sys_func
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private String sysFunc;
    
    
    private String projectCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.sys_code
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private String sysCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.is_main
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private Integer isMain2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dotp_pm_project_scope_sys.sys_func
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    private String sysFunc2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_sys.AI_ID
     *
     * @return the value of dotp_pm_project_scope_sys.AI_ID
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public Integer getAiId() {
        return aiId;
    }

    /**
	 * @return the sysName
	 */
	public String getSysName() {
		return sysName;
	}

	/**
	 * @param sysName
	 */
	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_sys.AI_ID
     *
     * @param aiId the value for dotp_pm_project_scope_sys.AI_ID
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public void setAiId(Integer aiId) {
        this.aiId = aiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_sys.project_code
     *
     * @return the value of dotp_pm_project_scope_sys.project_code
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_sys.project_code
     *
     * @param projectCode the value for dotp_pm_project_scope_sys.project_code
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_sys.sys_code
     *
     * @return the value of dotp_pm_project_scope_sys.sys_code
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_sys.sys_code
     *
     * @param sysCode the value for dotp_pm_project_scope_sys.sys_code
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_sys.is_main
     *
     * @return the value of dotp_pm_project_scope_sys.is_main
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public Integer getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_sys.is_main
     *
     * @param isMain the value for dotp_pm_project_scope_sys.is_main
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public void setIsMain(Integer isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dotp_pm_project_scope_sys.sys_func
     *
     * @return the value of dotp_pm_project_scope_sys.sys_func
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public String getSysFunc() {
        return sysFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dotp_pm_project_scope_sys.sys_func
     *
     * @param sysFunc the value for dotp_pm_project_scope_sys.sys_func
     *
     * @mbggenerated Thu Nov 13 22:52:37 CST 2014
     */
    public void setSysFunc(String sysFunc) {
        this.sysFunc = sysFunc;
    }

	/**
	 * @return  the projectCode2
	 */
	public String getProjectCode2() {
		return projectCode2;
	}

	/**
	 * @param projectCode2 the projectCode2 to set
	 */
	public void setProjectCode2(String projectCode2) {
		this.projectCode2 = projectCode2;
	}

	/**
	 * @return  the sysCode2
	 */
	public String getSysCode2() {
		return sysCode2;
	}

	/**
	 * @param sysCode2 the sysCode2 to set
	 */
	public void setSysCode2(String sysCode2) {
		this.sysCode2 = sysCode2;
	}

	/**
	 * @return  the isMain2
	 */
	public Integer getIsMain2() {
		return isMain2;
	}

	/**
	 * @param isMain2 the isMain2 to set
	 */
	public void setIsMain2(Integer isMain2) {
		this.isMain2 = isMain2;
	}

	/**
	 * @return  the sysFunc2
	 */
	public String getSysFunc2() {
		return sysFunc2;
	}

	/**
	 * @param sysFunc2 the sysFunc2 to set
	 */
	public void setSysFunc2(String sysFunc2) {
		this.sysFunc2 = sysFunc2;
	}
}