package com.deppon.dpm.webserviceclient.affiche.dip.integrateportal.informationcenter.bulletinmanage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2014-10-17T19:56:41.319+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebServiceClient(name = "InnerGgServiceService", 
                  wsdlLocation = "file:/D:/aa/InnerGgService.wsdl",
                  targetNamespace = "http://bulletinManage.informationCenter.integrateportal.dip") 
public class InnerGgServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bulletinManage.informationCenter.integrateportal.dip", "InnerGgServiceService");
    public final static QName InnerGgService = new QName("http://bulletinManage.informationCenter.integrateportal.dip", "InnerGgService");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/aa/InnerGgService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InnerGgServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/aa/InnerGgService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InnerGgServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InnerGgServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InnerGgServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns InnerGgService
     */
    @WebEndpoint(name = "InnerGgService")
    public InnerGgService getInnerGgService() {
        return super.getPort(InnerGgService, InnerGgService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InnerGgService
     */
    @WebEndpoint(name = "InnerGgService")
    public InnerGgService getInnerGgService(WebServiceFeature... features) {
        return super.getPort(InnerGgService, InnerGgService.class, features);
    }

}
