package com.deppon.dpm.webserviceclient.affiche.dip.integrateportal.informationcenter.bulletinmanage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2014-10-17T19:56:41.285+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://bulletinManage.informationCenter.integrateportal.dip", name = "InnerGgService")
@XmlSeeAlso({com.deppon.esb.header.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InnerGgService {

    @WebResult(name = "requestStrReturn", targetNamespace = "http://bulletinManage.informationCenter.integrateportal.dip", partName = "requestStrReturn")
    @WebMethod
    public java.lang.String queryInnerGg(
        @WebParam(partName = "requestStr", name = "requestStr", targetNamespace = "http://bulletinManage.informationCenter.integrateportal.dip")
        java.lang.String requestStr,
        @WebParam(partName = "esbHeader", name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        com.deppon.esb.header.ESBHeader esbHeader
    );
}
