//package com.deppon.fins.esb.mobile.mobileservice;
//
//import java.net.MalformedURLException;
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceFeature;
//import javax.xml.ws.Service;
//
///**
// * This class was generated by Apache CXF 2.6.7
// * 2014-04-18T14:25:06.265+08:00
// * Generated source version: 2.6.7
// * 
// */
//@WebServiceClient(name = "FinsMobileService", 
//                  wsdlLocation = "http://192.168.67.12:8580/esb2/ws/dpm2fin_self/queryWorkflow?wsdl",
//                  targetNamespace = "http://www.deppon.com/fins/esb/mobile/MobileService") 
//public class FinsMobileService extends Service {
//
//    public final static URL WSDL_LOCATION;
//
//    public final static QName SERVICE = new QName("http://www.deppon.com/fins/esb/mobile/MobileService", "FinsMobileService");
//    public final static QName MobileService = new QName("http://www.deppon.com/fins/esb/mobile/MobileService", "MobileService");
//    static {
//        URL url = null;
//        try {
//            url = new URL("http://192.168.67.12:8580/esb2/ws/dpm2fin_self/queryWorkflow?wsdl");
//        } catch (MalformedURLException e) {
//            java.util.logging.Logger.getLogger(FinsMobileService.class.getName())
//                .log(java.util.logging.Level.INFO, 
//                     "Can not initialize the default wsdl from {0}", "http://192.168.67.12:8580/esb2/ws/dpm2fin_self/queryWorkflow?wsdl");
//        }
//        WSDL_LOCATION = url;
//    }
//
//    public FinsMobileService(URL wsdlLocation) {
//        super(wsdlLocation, SERVICE);
//    }
//
//    public FinsMobileService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public FinsMobileService() {
//        super(WSDL_LOCATION, SERVICE);
//    }
//    
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public FinsMobileService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public FinsMobileService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public FinsMobileService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }
//
//    /**
//     *
//     * @return
//     *     returns IFinsMobileService
//     */
//    @WebEndpoint(name = "MobileService")
//    public IFinsMobileService getMobileService() {
//        return super.getPort(MobileService, IFinsMobileService.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns IFinsMobileService
//     */
//    @WebEndpoint(name = "MobileService")
//    public IFinsMobileService getMobileService(WebServiceFeature... features) {
//        return super.getPort(MobileService, IFinsMobileService.class, features);
//    }
//
//}
