package com.deppon.fins.esb.mobile.mobileservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.deppon.esb.header.ESBHeader;

/**
 * This class was generated by Apache CXF 2.6.7
 * 2014-04-18T14:25:06.218+08:00
 * Generated source version: 2.6.7
 * 
 */
@WebService(targetNamespace = "http://www.deppon.com/fins/esb/mobile/MobileService", name = "IFinsMobileService")
@XmlSeeAlso({com.deppon.fins.esb.mobile.domain.ObjectFactory.class, com.deppon.esb.exception.ObjectFactory.class, com.deppon.esb.header.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IFinsMobileService {

    @WebResult(name = "initWorkFlowViewDataResponse", targetNamespace = "http://www.deppon.com/fins/esb/mobile/domain/", partName = "response")
    @WebMethod(action = "http://www.deppon.com/fins/esb/mobile/FinsMobileService/initWorkFlowViewData")
    public com.deppon.fins.esb.mobile.domain.InitWorkFlowViewDataResponse initWorkFlowViewData(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "initWorkFlowViewDataRequest", targetNamespace = "http://www.deppon.com/fins/esb/mobile/domain/")
        com.deppon.fins.esb.mobile.domain.InitWorkFlowViewDataRequest request
    ) throws CommException;

    @WebResult(name = "approveResponse", targetNamespace = "http://www.deppon.com/fins/esb/mobile/domain/", partName = "response")
    @WebMethod(action = "http://www.deppon.com/fins/esb/mobile/FinsMobileService/approve")
    public com.deppon.fins.esb.mobile.domain.ApproveResponse approve(
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<ESBHeader> esbHeader,
        @WebParam(partName = "request", name = "approveRequest", targetNamespace = "http://www.deppon.com/fins/esb/mobile/domain/")
        com.deppon.fins.esb.mobile.domain.ApproveRequest request
    ) throws CommException;
}
