package com.deppon.dpm.webserviceclient.calendar.dip.portal.main.calendar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2014-10-17T20:00:31.107+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebServiceClient(name = "CalendarServiceService", 
                  wsdlLocation = "file:/D:/aa/CalendarService.wsdl",
                  targetNamespace = "http://calendar.main.portal.dip") 
public class CalendarServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://calendar.main.portal.dip", "CalendarServiceService");
    public final static QName CalendarService = new QName("http://calendar.main.portal.dip", "CalendarService");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/aa/CalendarService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalendarServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/aa/CalendarService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalendarServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalendarServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalendarServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CalendarService
     */
    @WebEndpoint(name = "CalendarService")
    public CalendarService getCalendarService() {
        return super.getPort(CalendarService, CalendarService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalendarService
     */
    @WebEndpoint(name = "CalendarService")
    public CalendarService getCalendarService(WebServiceFeature... features) {
        return super.getPort(CalendarService, CalendarService.class, features);
    }

}
