package com.deppon.dpm.webserviceclient.calendar.dip.portal.main.calendar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2014-10-17T20:00:31.091+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://calendar.main.portal.dip", name = "CalendarService")
@XmlSeeAlso({com.deppon.esb.header.ObjectFactory.class, com.deppon.dpm.webserviceclient.calendar.dip.portal.dataclient.json.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CalendarService {

    @WebResult(name = "requestStrReturn", targetNamespace = "http://calendar.main.portal.dip", partName = "requestStrReturn")
    @WebMethod
    public java.lang.String handleCalendar(
        @WebParam(partName = "requestStr", name = "requestStr", targetNamespace = "http://calendar.main.portal.dip")
        java.lang.String requestStr,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws JSONException;
}
